[0_(1)=RfcA(4){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$13=235(209):
>RfcA_yeast  {|294(332)|<Ascomycota(f)>}gi|584899|sp|P38630|RFC1_YEAST  Activator 1 95 kDa subunit (Replication factor C subunit 1) (Replication factor C1) (Cell division control protein 44) >gi|841462
{()DKLWTVKYAPTNLQQVCGNKGSVMKLKNWLANWEnskknsfkhagkdgsgvFRAAMLYGPPGIGKTTAAHLVAQE-----LGYDILEQNASDVRSKTLLNAGVKNALDNMSVVGYfkhneeaqnlngKHFVIIMDEVDGMSGgDRGGVGQLAQFCRKTSTPLILICNErNLPKMRPFDRVCLDIQFRRPDANSIKSRLMTIAIREKFKLDPNVIDRLIQTTRGDIRQVINLLSTISTTTK()}*

$14=244(209):
>RfcA_human  {|582(322)|<Chordata(m)>}gi|56757608|sp|P35251|RFC1_HUMAN  Activator 1 140 kDa subunit (Replication factor C large subunit) (A1 140 kDa subunit) (RF-C 140 kDa subunit) (Activator 1 large s
{()NLLWVDKYKPTSLKTIIGqqgDQSCANKLLRWLRNWQksssedkkhaakfgkfsgkddgssFKAALLSGPPGVGKTTTASLVCQE-----LGYSYVELNASDTRSKSSLKAIVAESLNNTSIKGFysngaassvsTKHALIMDEVDGMAGneDRGGIQELIGLIKHTKIPIICMCNDrNHPKIRSLVHYCFDLRFQRPRVEQIKGAMMSIAFKEGLKIPPPAMNEIILGANQDIRQVLHNLSMWCARSK()}*

$15=232(209):
>RfcA_plafa  {|349(323)|<Apicomplexa(E)>}gi|11999114|gb|AAG43050.1|  replication factor C subunit 1 [Plasmodium falciparum]
{()NQLWVEKYRPKNLNELVGNNQNVIKLQNWLASWEdvcikgikkpaqktfrgifenvnARCALLSGPAGIGKTTTAKIVSEA-----SGYNVIEFNASDERNKAAVEKISEMATGGYSIMSLnnrklTKTCIIMDEVDGMSSgDKGGSTAILKLIEKTKCPIICICNDrQNNKMRTLANKCYDLKFSMPQKNSVVKRLLEICKKEGIMMEPNALELLWESTCGDIRQMLNTLQLLSKT--()}*

$16=238(209):
>RfcA_arath  {|338(380)|<Streptophyta(V)>}gi|13374860|emb|CAC34494.1|  replication factor C large subunit-like protein [Arabidopsis thaliana] >gi|22326948|ref|NP_680188.1| AAA-type ATPase family protei
{()SLPWTEKYRPKVPNEIVGNQSLVTQLHNWLSHWHdqfggtgskgkgkklndagsKKAVLLSGTPGIGKTTSAKLVSQM-----LGFQAVEVNASDSRGKanSNIAKGIGGSNANSVKELVnneamaanfdrskHpKTVLIMDEVDGMSAgDRGGVADLIASIKISKIPIICICNDrYSQKLKSLVNYCLPLNYRKPTKQQMAKRLMHIAKAEGLEINEIALEELAERVNGDIRLAVNQLQYMS----()}*

_0].
[0_(1)=Ctf18(8){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=286(209):
>gi|74751544|sp|Q8WVB6|CTF18_HUMAN  {|278(411)|<Chordata(m)>}RecName: Full=Chromosome transmission fidelity protein 18 homolog; Short=hCTF18 >gi|17390405|gb|AAH18184.1| CTF18, chromosome transmission f
{()HCLWVDEFAPRHYTELLSDDFTNRCLLKWLKLWDlvvfgherpsrkprpsveparvskeatapgkwksheqvleemleagldpsqrpkQKVALLCGPPGLGKTTLAHVIARHA-----GYSVVEMNASDDRSPEVFRTRIEAATQMESVLGAggKPNCLVIDEIDGAPVAAINVLLSILNrkgpqevgpqgpavpsgggrrrraeGGLLMRPIICICNDqFAPSLRQLKQQAFLLHFPPTLPSRLVQRLQEVSLRQGMRADPGVLAALCEKTDNDIRACINTLQFLYSRGQ()}*

$3=316(209):
>gi|255554168|ref|XP_002518124.1|  {|211(286)|<Streptophyta(V)>}chromosome transmission fidelity factor, putative [Ricinus communis] >gi|223542720|gb|EEF44257.1| chromosome transmission fidelity factor
{()EQLWVDKYAPNSFTELLSDEQTNREVLLWLKQWDscvfgseirstsddilsslrrhstvsqhqklshsnfprrikghgwtngnfrhsnsldnensnvkgiqdlwskksrltgppeQKILLLCGPPGLGKTTLAHVAAKHC-----GYRVVEVNASDDRSSSTIEAKILDVVQMNSIMadS-RPKCLVIDEIDGALGDgkgAVEVILKMVSaerksntgkenvakgdqsgkisakkgrkTVSLSRPVICICNDlYAPVLRPLRQVAKVHIFVQPTVSRVVNRLKFICKKEGMKVSSIALTALADYAECDIRSCLNTLQFLHNK--()}*

$4=270(209):
>gi|157118491|ref|XP_001659132.1|  {|298(393)|<Arthropoda(M)>}hypothetical protein AaeL_AAEL008320 [Aedes aegypti] >gi|108875684|gb|EAT39909.1| conserved hypothetical protein [Aedes aegypti]
{()NSLWVEKYRPKRYVDLLSDETTNRSLLQWLKLWDkvvfgrepkekkdvkqlnsfnkktgrfesnggwkkknrsalnteldehgrpmQKVALLCGPPGLGKTTLAHTIARHA-----GYVVREVNASDDRSPEAFRIALESGTQMKSVLNEdkRPNCIVLDEIDGAPVATIDFLLKFISgsvsqkggkkgkgekteKFILKRPIICICNDmYVPALRQLRQIAFVVNFPPTECARLAERLLSIAKREKIETDLTSMLALADKSGNDVRSCLSMLQF------()}*

$5=254(209):
>gi|134117578|ref|XP_772560.1|  {|268(370)|<Basidiomycota(F)>}hypothetical protein CNBL0400 [Cryptococcus neoformans var. neoformans B-3501A] >gi|50255175|gb|EAL17913.1| hypothetical protein CNBL0400 [
{()TTMWVDKYRPKKFTDLLGEDRVHREVMSWLKEWDkcvfkrqqpqakkrpfdafdskpfpvdplgrphERVLLLSGPPGYGKTTLASIVARHA-----GYRILEINASDDRSYQTVQTRIRNAVDAGTSLGAegKPTCVVIDEIDGAGGGesgFIKALIKLI-qdvpakkksntpak--PLRRPIICICNDlYAPALRPLRSYARIIRFRKPQAQSLVVRLRDICKREGLQSDTRSLNTLVEMTSGDVRSCLNTLQFIKSRSS()}*

$6=249(209):
>gi|195999648|ref|XP_002109692.1|  {|225(332)|<Placozoa(M)>}hypothetical protein TRIADDRAFT_53969 [Trichoplax adhaerens] >gi|190587816|gb|EDV27858.1| hypothetical protein TRIADDRAFT_53969 [Trichoplax a
{()-SLWVDKYSPHHYRELLSDHSTNRSLLSWLKLWDktvfgkdfnipdetlanqlavdtqnrplKKVALLCGPPGLGKTTLAHVIARHA-----GYNVLEMNASDDRSVEIFRQRIESATQMHSIsgdeKG-LPNCLLIDEIDGAPTASVEVLIKFIRntenakvkkkskghQNILSRPIICICNDqYVPSLRQLRQHALVITFPPTSTNRLAGRLQDICRKEKLLTDLFALSALCSKAENDIRSCINTLQFLQRQSN()}*

$7=297(209):
>gi|115898584|ref|XP_780624.2|  {|289(419)|<Echinodermata(M)>}PREDICTED: similar to MGC81266 protein, partial [Strongylocentrotus purpuratus]
{()--LWVDKYAPKDYVDLLSDDGVNRNLLFWLKLWDhvvfgkevkqnktknkqekwkgggggggagagggagqqpnnfnkfkskfereledlelddqnrpkMKVALLCGPPGLGKTTLAHIIARHA-----GYNVIEMNASDDRSLEVFKNRLQSSIQMTSVLtpdQ-RPNCLVIDEIDGSPQGdwaKTRAAINCLLtvikgggdsnqaggggggkkrkkdQGPLKRPIICICNDvYVPALKQLRQLAYVTHFPPTAAARLAQRMYAISKRNQLQTDLTSLMALCVKADNDIRSCLNTLQFLQQQGK()}*

$8=300(209):
>gi|159467843|ref|XP_001692101.1|  {|613(577)|<Chlorophyta(V)>}DNA damage repair and chromosome cohesion protein [Chlamydomonas reinhardtii] >gi|158278828|gb|EDP04591.1| DNA damage repair and chromosom
{()-QLWVDKYAPRHFMSLLSDERTNRQVALWMKDWDecvfgrkagagankarggagtgplgakadtrpqNKVLLIGGPPGLGKTTLAHVVARHC-----GYHPYEINASDDRTAATLATKIQDAVQMTAVLGGgRPNCVIVDEIDGATGGteansAVAALMKIIKagdaapggsgrgagkaahagsdgedsdsdneggaggnkrggaggaagakrrggkSGaassrPLSRPIICIANDlYAPQLRPLRDVARVFTFTPPSSERLAARLQQICRAEGMEADPAALTLLVERTERDVRACLNTLQFLARR--()}*

$9=255(209):
>gi|1705792|sp|P49956|CTF18_YEAST  {|114(372)|<Ascomycota(f)>}RecName: Full=Chromosome transmission fidelity protein 18 >gi|807960|emb|CAA89224.1| Chl12p [Saccharomyces cerevisiae] >gi|190408309|gb|EDV
{()--LWVEKWRPKKFLDLVGNEKTNRRMLGWLRQWTpavfkeqlpklptekevsdmeldplkrppKKILLLHGPPGIGKTSVAHVIAKQS-----GFSVSEINASDERAGPMVKEKIYNLLFNHTFDT-NPVCLVADEIDGSIESgFIRILVDIMQsdikatnkllygqpdkkdkkrkkkrSKLLTRPIICICNNlYAPSLEKLKPFCEIIAVKRPSDTTLLERLNLICHKENMNIPIKAINDLIDLAQGDVRNCINNLQFLASN--()}*

_0].
[0_(1)=RfcBCD(12){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=211(209):
>RfcB_yeast  {|7(0)|<Ascomycota(f)>}RFC4_YEAST  Activator 1 37 kDa subunit (Replication factor C subunit 4) (Replication factor C4) >gi|841468|gb|AAC49063.1| Rfc4p >gi|626874|pir||A53845 replication 
{()QLPWVEKYRPQVLSDIVGNKETIDRLQQIAKDGNMPHMIISGMPGIGKTTSVHCLAHELLGRSYADGVLELNASDDRGIDVVRNQIKHFAQKKLHLPpGKHKIVILDEADSMTAGAQQALRRTMELYSNSTRFAFACNQSNKIIEPLQSRCAILRYSKLSDEDVLKRLLQIIKLEDVKYTNDGLEAIIFTAEGDMRQAINNLQsTVAGHGL()}*

$2=318(316):
>RfcB_human  {<Chordata(m)>}RFC2_HUMAN  Activator 1 40 kDa subunit (Replication factor C 40 kDa subunit) (A1 40 kDa subunit) (RF-C 40 kDa subunit) (RFC40) >gi|2914760|gb|AAC04860.1| replicatio
{(HY)ELPWVEKYRPVKLNEIVGNEDTVSRLEVFAREGNVPNIIIAGPPGTGKTTSILCLARALLGPALKDAMLELNASNDRGIDVVRNKIKMFAQQKVTLPkGRHKIIILDEADSMTDGAQQALRRTMEIYSKTTRFALACNASDKIIEPIQSRCAVLRYTKLTDAQILTRLMNVIEKERVPYTDDGLEAIIFTAQGDMRQALNNLQsTFSGFGF(INSENVFKVCDEPHPLLVKEMIQHCVNANIDEAYKILAHLWHLGYSPEDIIGNIFRVCKTFQMAEYLKLEFIKEIGYTHMKIAEGVNSLLQMAGLLARLCQKTMA)}*

$3=319(317):
>RfcB_plafa  {<Apicomplexa(e)>}Plasmodium  gi|23509093|ref|NP_701761.1| replication factor c subunit 4 [Plasmodium falciparum 3D7] >gi|23496934|gb|AAN36485.1| replication factor c subunit 4 [Plasmodium
{(RN)IDIWIEKYRPEFLDEVVGNPFVINTLKSIITSGNMPNLLLAGAPGTGKTTSILCLASEMLGNQAKKAVLELNASDDRGINVIRDRIKSFAKEIISLPpGKHKIIILDEVDSMTTAAQQSLRRIMELYSDTTRFALACNQSEKIIDALQSRCAIIRYFKLSDDQVLKRILKICDLENIKYTDDGLDALTFIADGDLRKAVNCLQsTYAGLEV(INKENVLHICDIPSPERIENLLKHCVNSEWKKAHDIAYSMIKEGHTPYDISLTSSNVLRRFNIGSEVIQIEFLKIGAMACNTMATGLTSVIQLDKLLADWCMAAKI)}*

$4=318(316):
>RfcB_arath  {<Streptophyta(v)>}gi|12323266|gb|AAG51618.1 replication factor, putative; 74998-73295 [Arabidopsis thaliana] >gi|15221697|ref|NP_176504.1| replication factor C 40 kDa, putative [Arabidops
{(GY)NEPWVEKYRPSKVVDIVGNEDAVSRLQVIARDGNMPNLILSGPPGTGKTTSILALAHELLGTNYKEAVLELNASDDRGIDVVRNKIKMFAQKKVTLPpGRHKVVILDEADSMTSGAQQALRRTIEIYSNSTRFALACNTSAKIIEPIQSRCALVRFSRLSDQQILGRLLVVVAAEKVPYVPEGLEAIIFTADGDMRQALNNLQaTFSGFSF(VNQENVFKVCDQPHPLHVKNIVRNVLESKFDIACDGLKQLYDLGYSPTDIITTLFRIIKNYDMAEYLKLEFMKETGFAHMRICDGVGSYLQLCGLLAKLSIVRET)}*

$5=211(211):
>RfcC_yeast  {|9(120)|<Ascomycota(f)>}RFC3_YEAST  Activator 1 40 kDa subunit (Replication factor C subunit 3) (Replication factor C3) >gi|1050872|gb|AAC49110.1| replication factor C, 40 kDa subunit >gi
{(KE)NLPWVEKYRPETLDEVYGQNEVITTVRKFVDEGKLPHLLFYGPPGTGKTSTIVALAREIYGKNYSNMVLELNASDDRGIDVVRNQIKDFASTRQIFSKGFKLIILDEADAMTNAAQNALRRVIERYTKNTRFCVLANYAHKLTPALLSRCTRFRFQPLPQEAIERRIANVLVHEKLKLSPNAEKALIELSNGDMRRVLNVLQSCKATLD()}*

$6=212(211):
>RfcC_human  {|16(112)|<Chordata(m)>}RFC5_HUMAN  Activator 1 36 kDa subunit (Replication factor C 36 kDa subunit) (A1 36 kDa subunit) (RF-C 36 kDa subunit) (RFC36) (Replication factor C subunit 5) >gi|
{(IR)NLPWVEKYRPQTLNDLISHQDILSTIQKFINEDRLPHLLLYGPPGTGKTSTILACAKQLYKDkEFGSMVLELNASDDRGIDIIRGPILSFASTRTIFKKGFKLVILDEADAMTQDAQNALRRVIEKFTENTRFCLICNYLSKIIPALQSRCTRFRFGPLTPELMVPRLEHVVEEEKVDISEDGMKALVTLSSGDMRRALNILQSTNMAFG()}*

$7=281(277):
>RfcC_plafa  {|9(0)|<Apicomplexa(e)>}Plasmodium  gi|23509823|ref|NP_702490.1| replication factor C3 [Plasmodium falciparum 3D7] >gi|23497675|gb|AAN37214.1| replication factor C3 [Plasmodium falciparum 
{(SE)LTPWVEKYRPNVLNDIISHEQVISTIKRFVQKGELPHLLLHGPPGTGKTSTILAVCKELYGDKRSSFVLELNASDDRGINVIRDQIKTFAESKNHYTTCekttLKLIILDEADHMTYPAQNAMRRIMENYAKNVRFCLLCNYVNKITPAIQSRCTAFRFAPLKKEYMKNKALDIAKSENVNLTEGGIDSLIRVGHGDMRRILNCLQVVSLSHK(NLVIDENVILSTLDIPLPSETKKILEYFTKGSIKESYEFVSNLQYDKGYSTKDIMMCLYESVLTYD)}*

$8=285(283):
>RfcC_arath  {|35(0)|<Streptophyta(v)>}gi|21436375|gb|AAM51357.1| putative replication factor C [Arabidopsis thaliana] 
{(SK)ATPWVEKYRPQSLDDVAAHRDIIDTIDRLTNENKLPHLLLYGPPGTGKTSTILAVARKLYGPKYRNMILELNASDDRGIDVVRQQIQDFASTQSFSLGKssVKLVLLDEADAMTKDAQFALRRVIEKYTKSTRFALIGNHVNKIIPALQSRCTRFRFAPLDGVHMSQRLKHVIEAERLVVSDCGLAALVRLSNGDMRKALNILQSTHMASK(EITEEESKQITEEDVYLCTGNPLPKDIEQISHWLLNKPFDECYKDVSEIKTRKGLAIVDIVKEITLFIFKIK)}*

$9=222(211):
>RfcD_yeast  {|21(0)|<Ascomycota(f)>}RFC2_YEAST  Activator 1 41 kDa subunit (Replication factor C subunit 2) (Replication factor C2) >gi|498463|dbj|BAA05858.1| Rfc2 protein [Saccharomyces cerevisiae] >
{(LA)QQPWVEKYRPKNLDEVTAQDHAVTVLKKTLKSANLPHMLFYGPPGTGKTSTILALTKELYGpDLMKSRILELNASDERGISIVREKVKNFARLtvskpskhdleNYPC-PPYKIIILDEADSMTADAQSALRRTMETYSGVTRFCLICNYVTRIIDPLASRCSKFRFKALDASNAIDRLRFISEQENVKCDDGVLERILDISAGDLRRGITLLQSASKGAQ()}*

$10=219(211):
>RfcD_human  {|34(0)|<Chordata(m)>}RFC4_HUMAN  Activator 1 37 kDa subunit (Replication factor C 37 kDa subunit) (A1 37 kDa subunit) (RF-C 37 kDa subunit) (RFC37) >gi|1498256|gb|AAB09785.1| rep
{(AK)PVPWVEKYRPKCVDEVAFQEEVVAVLKKSLEGADLPNLLFYGPPGTGKTSTILAAARELFGpELFRLRVLELNASDERGIQVVREKVKNFAQLtvsgsrsdGKPC-PPFKIVILDEADSMTSAAQAALRRTMEKESKTTRFCLICNYVSRIIEPLTSRCSKFRFKPLSDKIQQQRLLDIAKKENVKISDEGIAYLVKVSEGDLRKAITFLQSATRLTG()}*

$11=222(211):
>RfcD_plafa  {<Apicomplexa(e)>}Plasmodium  gi|16805067|ref|NP_473096.1| replication factor C, subunit 2 [Plasmodium falciparum 3D7] >gi|3845290|gb|AAC71957.1| replication factor C, subunit 2 [Plasmodiu
{(ME)NIPWVEKYRPKRLDDIVHQNNAVMMLKEVVRTKNMPHLIFHGPPGTGKTSAINALAHELFGkENISERVLELNASDDRGINVVREKIKAYTRIsisknkihseTKEVLPSWKLVVLDEADMMTEDAQSALRRIIEIYSNVTRFILICNYIHKISDPIFSRCSCYRFQSIPINIKKEKLLYICQNENIDIVDDALEKIIETTEGDLRRAVSILQLCSCINT()}*

$12=220(211):
>RfcD_arath  {|5(0)|<Streptophyta(v)>}gi|34098857|gb|AAQ56811.1| At1g21690 [Arabidopsis thaliana] >gi|15810343|gb|AAL07059.1| putative replication factor [Arabidopsis thaliana] >gi|21536935|gb|AAM61276
{(QS)SQPWVEKYRPKQVKDVAHQEEVVRVLTNTLQTADCPHMLFYGPPGTGKTTTALAIAHQLFGpELYKSRVLELNASDDRGINVVRTKIKDFAAVavgsnhrqsGYPC-PSFKIIILDEADSMTEDAQNALRRTMETYSKVTRFFFICNYISRIIEPLASRCAKFRFKPLSEEVMSNRILHICNEEGLSLDGEALSTLSSISQGDLRRAITYLQSATRLFG()}*

_0].
[0_(1)=RfcE(4){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$18=245(209):
>RfcE_yeast  {|0(109)|<Ascomycota(f)>}RFC5_YEAST Activator 1 40 kDa subunit (Replication factor C subunit 5) (Replication factor C5) >gi|841471|gb|AAC49065.1| Rfc5p >gi|6319562|ref|NP_009644.1
{()MSLWVDKYRPKSLNALSHNEELTNFLKSLSdQPRDLPHLLLYGPNGTGKKTRCMALLESIFGpgvyrlkidvrqfvtasnrklelnVVSSPYHLEITPSDMGNNDriVIQELLKEVAQMEQVdfqdskdgLAHRYKCVIINEANSLTKDAQAALRRTMEKYSKNIRLIMVCDSMSPIIAPIKSRCLLIRCPAPSDSEISTILSDVVTNERIQLeTKDILKRIAQASNGNLRVSLLMLESMALNNE()}*

$19=238(209):
>RfcE_human  {|0(11)|<Chordata(M)>}gi|3915601|sp|P40938.2|RFC3_HUMAN  Full=Replication factor C subuni
{()MSLWVDKYRPCSLGRLDYHKEQAAQLRNLVQCGDFPHLLVYGPSGAGKKTRIMCILRELYGvgveklriehQTITTpskkkieistiasnYHLEVNP
SDAGNSDrvVIQEMLKTVAQSQQLetnSQRDFKVVLLTEVDKLTKDAQHALRRTMEKYMSTCRLILCCNSTSKVIPPIRSRCLAVRVPAPSIEDICHVLS
TVCKKEGLNLPSQLAHRLAEKSCRNLRKALLMCEACRVQQY()}*

$20=237(209):
>RfcE_plafa  {|0(112)|<Apicomplexa(E)>}gi|23508310|ref|NP_700979.1| replication factor C subunit 5, putative [Plasmodium falciparum 3D7] 
{()--MWLEKYSPQSIDELTIHKDITERLRKLSRHKDLPHIIFYGAPGGGKSTRINCLIKEIFKDekiirrpecitnaenkininvVQSNYHLELQCFELGNKDkiIVQSIIKELCSYKSSASffsktPMYRIFVFKDAEFLSEGAQAGLRRTLETYIRNARVILHLEHLSKIIEPLKSRCICIRVPLPSEEEIYSVLQNICKQENVSpsfSTYEYFQTLINTHGRNLRKCIMALEMSVYAN-()}*

$21=240(209):
>RfcE_arath  {|0(114)|<Streptophyta(V)>}gi|20259637|gb|AAM14175.1| putative replication factor C [Arabidopsis thaliana] 
{()-MLWVDKYRPKSLDKVIVHEDIAQKLKKLVSEQDCPHLLFYGPSGSGKKTLIMALLKQIYGAsaekvkvenrawkvdagsrtidlelttLSSTNHVELTPSDAGFQDryIVQEIIKEMAKNRPIdtkGKKGYKVLVLNEVDKLSREAQHSLRRTMEKYSSSCRLILCCNSSSKVTEAIKSRCLNVRINAPSQEEIVKVLEFVAKKESLQLPQGFAARIAEKSNRSLRRAILSLETCRVQNY()}*

_0].
[0_(1)=MiscRfc(3){go=19,gx=2,pn=5.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=209(209):
>RfcBCD consensus seq
{()NLPWVEKYRPKTLDDVVGQEDVVSTLKKFAREGNLPHLLFYGPPGTGKTSTILALARELYGDNYKSRVLELNASDDRGIDVVRNKIKDFAQTKKPLPGKHKIV
ILDEADSMTADAQNALRRTMEKYSKSTRFCLICNYSSKIIEPLQSRCAKFRFKPLSDEQMLNRLLHICEAENVKYSDDGLEALIFTSEGDMRRALNNLQSASGLGG
()}*

$1=209(209):
>RfcA consensus seq
{()NLLWTEKYRPTNLNEIVGNQSCVTKLQNWLANWEFKAALLSGPPGIGKTTTAKLVSQEXXXXXLGYSAVEQNASDSRSKSALAAGVGGALGNSSIEGYTKTVI
IMDEVDGMSGDRGGVGALIGLIKKTKIPIICICNDNSPKMRSLVNYCLDLNFRRPTKNSIKKRLMSIAKKEGLKINPNALEELIEGTNGDIRQVLNTLSTWSATSK
()}*

$1=209(209):
>RfcE consensus seq
{()MSLWVDKYRPKSLDALSHHEDIAAQLKKLSQCGDLPHLLFYGPSGGGKKTRIMCLLKEIYGAVSSTYHLELTPSDAGNSDVVQEIIKEVAQSEQSGAKGYKVV
VLNEADKLSKDAQAALRRTMEKYSSNCRLILCCNSSSKVIEPIKSRCLCVRVPAPSDEEICSVLSTVCKKEGLQLTSGYAARIAEKSNRNLRKAILMLEACRVQNY
()}*

_0].
[0_(1)=Gamma(14){go=19,gx=2,pn=5.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=229(209):
>gi|72160455|ref|YP_288112.1|  {|1(462)|<Actinobacteria(B)>}ATPase [Thermobifida fusca YX] >gi|71914187|gb|AAZ54089.1| ATPase [Thermobifida fusca YX]
{()SIALYRKYRPATFAEVRGQEHVTEPLRQALRNGRVNHaYLFSGPRGCGKTSSARILARSLNcakgptpdpcgecdscvalAPDGggSIDVIEIDAASHGGVDDARD-LRERAFFAPVNS-RYKVYIIDEAHMVTREGFNALLKLVEEPPPHLKFVFATTEPEKVIGTIRSRTHHYPFRLIPPNTLRELIEEILNEEKVPYDPAALPLVIRAGGGSARDTLSILDQLLAGSD()}*

$2=227(209):
>gi|42735016|gb|AAS38956.1|  {|2(333)|<Firmicutes(B)>}DNA polymerase III, gamma and tau subunits [Bacillus cereus ATCC 10987] >gi|42779101|ref|NP_976348.1| DNA polymerase III, gamma and tau subunits [B
{()YQALYRTWRPQKFEDVVGQKHVTKTLQNALLQEKVSHaYLFSGPRGTGKTTIAKVFAKAINcehapvaepcnecpsclgiTQGSISDVLEIDAASNNGVDEIRD-IRDKVKYAPSAV-EYKVYIIDEVHMLSMGAFNALLKTLEEPPGHVIFILATTEPHKIPPTIISRCQRFEFRKISVNDIVERLSTVVNNEGTQVEDEALQIVARAAEGGMRDALSLIDQAISYSD()}*

$3=227(209):
>gi|15606894|ref|NP_214275.1|  {|2(244)|<Aquificae(B)>}DNA polymerase III gamma subunit [Aquifex aeolicus VF5] >gi|2984127|gb|AAC07663.1| DNA polymerase III gamma subunit [Aquifex aeolicus VF5] >gi|751
{()YVPFARKYRPKFFREVIGQEAPVRILKNAIKNDRVAHaYLFAGPRGVGKTTIARILAKALNcknpskgepcgecencreiDRGVFPDLIEMDAASNRGIDDVRA-LKEAVNYKPIKG-KYKVYIIDEAHMLTKEAFNALLKTLEEPPPRTVFVLCTTEYDKILPTILSRCQRIIFSKVRKEKVIEYLKKICEKEGIECEEGALEVLAHASEGCMRDAASLLDQASVYGE()}*

$4=227(209):
>gi|37521178|ref|NP_924555.1|  {|2(403)|<Cyanobacteria(B)>}DNA polymerase III gamma and tau subunits [Gloeobacter violaceus PCC 7421] >gi|35212174|dbj|BAC89550.1| DNA polymerase III gamma and tau subun
{()YEPLHHKYRPQRFGDVVGQGPIVTTLTNALKAGRIAHaYLFTGSRGTGKTTTARLIAKALNcihgptpdpcgrceqclaiATGSALDVIEIDAASNTGVDNIRE-LIERAQFAPVQS-RQKVYILDEVHMLSSAAFNCLLKTLEEPPAHVTFVLATTDPQKVLPTVISRCQRFDFRRIPLTDMVKHLEEIAWKEDIDIEHEAVELVAQIAQGGLRDAESLLDQLALLEG()}*

$5=233(209):
>gi|21674147|ref|NP_662212.1|  {|2(385)|<Chlorobi(B)>}DNA polymerase III, gamma/tau subunit [Chlorobium tepidum TLS] >gi|21647307|gb|AAM72554.1| DNA polymerase III, gamma and tau subunits [Chlorobium t
{()YQVIARKYRPSRFADITAQEHITGTIQNSLRMGRVGHgYIFSGLRGVGKTTAARVFAKAVNcqrmiddpqylkevtepcgvcescrdfDAGASLNISEFDAASNNSVDDIRL-LRENVRYGPQKG-RYRVYIIDEVHMLSTAAFNAFLKTLEEPPPHAIFIFATTELHKIPATIASRCQRFNFKRIPLDRIQGQLRQICDAEGITADADALQLIARKAQGSMRDAQSILDQVIAF--()}*

$6=227(209):
>gi|24217030|ref|NP_714511.1|  {|28(248)|<Spirochaetes(B)>}DNA polymerase III subunit gamma [Leptospira interrogans serovar Lai str. 56601] >gi|24198439|gb|AAN51529.1| DNA polymerase III subunit gamma 
{()HEVLSRKYRPQKFRDVIHQDLAIGALQNALKSGKIGHaYIFFGPRGVGKTTIARILAKRLNcqnpidnepcnecnscseiTRGISSDVLEIDAASNRGIENIRE-LRDNVKFAPMGG-KYKVYIIDEVHMLTDQSFNALLKTLEEPPAHIVFVLATTEFHKIPETILSRCQDFIFKKVPLSVLQDYSEKLCKIENVQYDQEGLFWVAKKGDGSVRDMLSFMEQAIVFTD()}*

$7=227(209):
>gi|4981209|gb|AAD35768.1|  {|0(251)|<Thermotogae(B)>}DNA polymerase III, gamma and tau subunit [Thermotoga maritima MSB8] >gi|15643449|ref|NP_228495.1| DNA polymerase III, gamma and tau subunit [Therm
{()MEVLYRKYRPKTFSEVVNQDHVKKAIIGAIQKNSVAHgYIFAGPRGTGKTTLARILAKSLNcenrkgvepcnscracreiDEGTFMDVIELDAASNRGIDEIRR-IRDAVGYRPMEG-KYKVYIIDEVHMLTKEAFNALLKTLEEPPSHVVFVLATTNLEKVPPTIISRCQVFEFRNIPDELIEKRLQEVAEAEGIEIDREALSFIAKRASGGLRDALTMLEQVWKFSE()}*

$8=228(209):
>gi|29338918|gb|AAO76717.1|  {|3(388)|<Bacteroidetes(B)>}DNA polymerase III subunit gamma/tau [Bacteroides thetaiotaomicron VPI-5482] >gi|29347020|ref|NP_810523.1| DNA polymerase III subunit gamma/tau 
{()YIVSARKYRPSTFESVVGQRALTTTLKNAIATQKLAHaYLFCGPRGVGKTTCARIFAKTINcmtpttdgeacnecescvafNEQRSYNIHELDAASNNSVDDIRQ-LVEQVRIPPQIG-KYKVYIIDEVHMLSASAFNAFLKTLEEPPRHAIFILATTEKHKILPTILSRCQIYDFNRISVEDTVNHLSYVAAKENITAEPEALNVIAMKADGGMRDALSIFDQVVSFTG()}*

$9=227(209):
>gi|32444837|emb|CAD74839.1|  {|36(413)|<Planctomycetes(B)>}DNA polymerase III gamma and tau subunits [Rhodopirellula baltica SH 1] >gi|32474299|ref|NP_867293.1| DNA polymerase III gamma and tau subuni
{()YVVVARRYRPRDFTQLVGQDHVARALQGAIETSRVGHaYLFTGARGVGKTSTARIFAKALNhpdgptanpdsesdvaqaiDSGEDVDVIEIDGASNRGIDEIRS-LRANVGVRPSRS-RYKIYIIDEVHMLTGAAFNALLKTLEEPPEHVKFIFCTTDPEKIPITVLSRCQRFDFAPVESDKIVQRLREIVEAEDNTVEDEALELLARRAAGSMRDSQSLLEQVLSFSD()}*

$10=221(209):
>gi|29840095|ref|NP_829201.1|  {|5(220)|<Chlamydiae(B)>}DNA polymerase III, gamma subunit [Chlamydophila caviae GPIC] >gi|29834443|gb|AAP05079.1| DNA polymerase III, gamma subunit [Chlamydophila caviae
{()YQVSSRKYRPQTFSEILGQDAVVTVLKNALQFQRVAHaYLFSGIRGTGKTTLARIFAKALNcpertsdhepcnhccickeiSSGTSLDVIEIDGASHRGIEDIRQ-INETVLFTPAKS-QYKIYIIDEVHMLTKEAFNSLLKTLEEPPSHVKFFLATTENYKIPGTILSRCQKMYLKRIPETMIVEKLASISKENSIETSSEALLPIARAAQGSLRDAESLYD-------()}*

$11=224(209):
>gi|19713068|gb|AAL93929.1|  {|1(259)|<Fusobacteria(B)>}DNA polymerase III subunits gamma and tau [Fusobacterium nucleatum subsp. nucleatum ATCC 25586] >gi|19705135|ref|NP_602630.1| DNA polymerase III 
{()HITLYRKYRPSSFSEVSGENEIVKSLKLSLKNKSMAHaYLFSGPRGVGKTTIARLIAKGVNclnlketgepcnecknckaiNEGRFSDLIEIDAASNRSIDEIRS-LKEKINYQPVEG-LKKVYIIDEAHMLTKEAFNALLKTLEEPPAHVMFILATTELEKILPTIISRCQRYDFKPLDLEEMKLGLEHILKEENLSMTDDVYPVIYENSSGSMRDSISILERLI----()}*

$12=223(209):
>gi|15807400|ref|NP_296131.1|  {|2(390)|<Deinococcus(B)>}DNA polymerase III, tau/gamma subunit [Deinococcus radiodurans R1] >gi|6460225|gb|AAF11953.1| DNA polymerase III, tau/gamma subunit [Deinococcus
{()--AIYQRARPIRWEDVVGQEHVKDVLRTALEQGRIGHaYLFSGPRGVGKTTTARLIAMTANctgpapkpcgecesclavRAGSHPDVMEIDAASNNSVDDVRD-LREKVGLAAMRG-GKKIYILDEAHMMSRAAFNALLKTLEEPPEHVIFILATTEPEKIIPTILSRCQHYRFRRLTSEEIAGKLAGLVTLEGASADPDALNLIGRLADGAMRDGESLLERMLAAG-()}*

$13=225(209):
>gi|76260080|ref|ZP_00767721.1|  {|14(370)|<Chloroflexi(B)>}AAA ATPase, central region [Chloroflexus aurantiacus J-10-fl] >gi|76165030|gb|EAO59169.1| AAA ATPase, central region [Chloroflexus aurantiacu
{()-QSLYRKWRSQTFAELVGQEHVVQTLRNAIAEDRVGHaYLFTGPRGVGKTTMARLLAKAVNclnpdptarpcgvcemcaaiAEGRAVDVIEMDAASHTSVEDARE-IIERVQFRPAEA-RMKVYIIDETHMLSTAAFNALLKTLEEPPDHALFILATTEVHKVPATILSRCQRFTFVRHSVSAMAAHLRRIAAAEGIVLADGVPEAIARAATGSMRDALGILEQLASF--()}*

$14=227(209):
>gi|30749632|pdb|1NJF|D  {|2(14)|<Proteobacteria(b)>}Chain D, Nucleotide Bound Form Of An Isolated E. Coli Clamp Loader Gamma Subunit >gi|30749631|pdb|1NJF|C Chain C, Nucleotide Bound Form Of An Isolat
{()YQVLARKWRPQTFADVVGQEHVLTALANGLSLGRIHHaYLFSGTRGVGKTSIARLLAKGLNcetgitatpcgvcdncreiEQGRFVDLIEIDAASRTKVEDTRD-LLDNVQYAPARG-RFKVYLIDEVHMLSRHSFNALLKTLEEPPEHVKFLLATTDPQKLPVTILSRCLQFHLKALDVEQIRHQLEHILNEEHIAHEPRALQLLARAAEGSLRDALSLTDQAIASGD()}*

_0].
[0_(1)=DeltaPrime(9){go=19,gx=2,pn=5.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=213(209):
>gi|61679679|pdb|1XXI|J  {|0(121)|<Proteobacteria(b)>}Chain J, Adp Bound E. Coli Clamp Loader Complex >gi|61679674|pdb|1XXI|E Chain E, Adp Bound E. Coli Clamp Loader Complex >gi|15988196|pdb|1JR3|E Cha
{()MRW------------YPWLRPDFEKLVASYQAGRGHHaLLIQALPGMGDDALIYALSRYLLcqqpqghkscghcrgcqlmQAGTHPDYYTLAPEKgknTLGVDAVRE-VTEKLNEHARLGGA-KVVWVTDAALLTDAAANALLKTLEEPPAETWFFLATREPERLLATLRSRCRLHYLAPPPEQYAVTWLSR-----EVTMSQDALLAALRLSAGSPGAALALFQGDNWQAR()}*

$2=237(209):
>gi|32447180|emb|CAD77006.1|  {|29(110)|<Planctomycetes(B)>}DNA polymerase III, tau/gamma subunit [Rhodopirellula baltica SH 1] >gi|32476634|ref|NP_869628.1| DNA polymerase III, tau/gamma subunit [Rhod
{()WND------------LIGHDALITGLTAAIRQGRLGGsLLFVGPNGVGKTSAAILLTQTLLcerstardmapcgecpscvqvRVGTHPDFIQVRKPDdktLIPLElligpvDARlqeG-FCHDVHLRPMQAQR-KVAILHDADFLNEEGANCLLKTLEEPPANALIILIGSSEQRQLPTIRSRCQVLRFQTPPGEAGRALLRK-----QLDhyqsqheeeslptMSDDALDAAIELSAGDMHVAARLARGGGEQIR()}*

$3=209(209):
>gi|67917097|ref|ZP_00510772.1|  {|2(118)|<Firmicutes(B)>}DNA-directed DNA polymerase [Clostridium thermocellum ATCC 27405] >gi|67848956|gb|EAM44592.1| DNA-directed DNA polymerase [Clostridium thermoce
{()FNS------------IIGQKSVVESLKRFIDNNRIGHaYIFSGPEGIGKSTVAKIFASILMcddaavdkscgncrscrlfENRTNPDFGVLETRGls-IGVDEIRN-LQQDICIRPLYSKR-KVYLIREAEKMTVQAQNCLLKTLEEPPEYAVIILATSNYESLLETIRSRSVRINFAKNTFDEVKRFIVS-----RAGGDFEQADFIAAYADGVIGRAVELMESERFK--()}*

$4=255(209):
>gi|21674424|ref|NP_662489.1|  {|2(133)|<Chlorobi(B)>}DNA polymerase III, delta subunit, putative [Chlorobium tepidum TLS] >gi|21647607|gb|AAM72831.1| DNA polymerase III, delta subunit, putative [Chlor
{()WNS------------IVGHEPQLRVLKTALGANRLAHaYLFTGPEGSGKESVAFELAKILNcrssgnlsgegscgecescrqtDLLMHPNIEYLFPVEaalLetidpskkenkklteareryealldekrknpfftpamersmgILTEQVVM-LQQKASLAPRDGGK-KVFIISQAERLHPTAANKLLKLLEEPPAHVVFILVSSRPESVLPTIRSRCQLLNFARPRPAEIEAWIAR-----RApQLDKTERHFIVSLSRGNLCSALELIEAET----()}*

$5=248(209):
>gi|34540688|ref|NP_905167.1|  {|37(131)|<Bacteroidetes(B)>}DNA polymerase III, delta prime subunit, putative [Porphyromonas gingivalis W83] >gi|34397002|gb|AAQ66066.1| DNA polymerase III, delta prime 
{()FRD------------VAGLEDLKTYLRRTAQTRQIAHaQLFAGEEGGGAFPLALAYARYLNcqmptdtdacghcpscvkyDALAHPDLFFVYPVVnasSSPapsddyIRQWREMlgsesyftpadwleyikagnsqpiiyskeaeaVEQKLSFRIYEASY-RVVMIWQPERMNEAMANKLLKLIEEPPEHTLFFMISSEPDKVLGTIRSRTQLINVRLLHEIEIVEALSR-----NNQGNTADIIRIAHLAEGNYRRAMDLYRGEW----()}*

$6=205(209):
>gi|46400347|emb|CAF23796.1|  {|7(157)|<Chlamydiae(B)>}putative DNA polymerase III, delta' subunit, holB [Parachlamydia sp. UWE25] >gi|46446706|ref|YP_008071.1| putative DNA polymerase III, delta' subu
{()FSF------------LVGNDPIKIYLQRMLIKKAIGNsLLFAGPNGVGKGLFAYALASQLIceqeeknkykiENGLHPDIHIYRPEGklgLHGIQSLRE-LSEEVHLPPYEASW-KIFIIHDAERMLSVSANTLLKTFEEPPPKTVIILLSQSQAALLPTIVSRCRTLHFQPIHASEIEKVLVE-----RMYLETEFAQNIASLSQGSLGRAVQLIQKKGDESR()}*

$7=216(209):
>gi|76259634|ref|ZP_00767281.1|  {|0(124)|<Chloroflexi(B)>}DNA polymerase III delta prime subunit [Chloroflexus aurantiacus J-10-fl] >gi|76165535|gb|EAO59668.1| DNA polymerase III delta prime subunit [
{()MWH------------VYGHEWAIEQLRSNIRSQQVAHaYLFAGPQGLGKSLLALRMAQALLcerqtgdpclqcrscrriDHGSHPDVRIAGMETqaaaakaedaarqkELKIATIRE-WQRDLALRPYEAPR-RVLILHDADRLSEEAANAMLKTLEEPPDYATLLLVAHS-NELLPTIVSRCRVLRLRPLPREQVASALRD-----QG-ASKDQAEILAAWSNGRIGWAINLFNDP-----()}*

$8=217(209):
>gi|75812745|ref|YP_320362.1|  {|5(85)|<Cyanobacteria(B)>}DNA polymerase III, delta prime subunit [Anabaena variabilis ATCC 29413] >gi|75705501|gb|ABA25173.1| DNA polymerase III, delta prime subunit [A
{()FTE------------IIGQHTAKLLLTEAIERNQIAPaYLFSSEvEGVGKGKIALAFANAILsrgsrsamakhlpppkgdaqgtasaGESKHLDILQIKPTYtenTsqqksvpaIRVEQMRE-VIEFLSTSAVEGKQ-KVVIIYEADMLNPTAANKLLKTLEEPKTGT-FILISSYPQKLLPTIKSRCQIIPFQRLTDEEVISVLKD-----QQIEATEK---ILAISSGSPGQAIANIK-------()}*

$9=218(209):
>gi|50841736|ref|YP_054963.1|  {|0(181)|<Actinobacteria(B)>}ATPase [Propionibacterium acnes KPA171202] >gi|50839338|gb|AAT82005.1| ATPase [Propionibacterium acnes KPA171202]
{()-------MLTGVWADLVGQEKAVGVLRRAAesqpgrsSHAMSHAWLITGPPGSGRSNAAKAFAAALQcvdhgcgqcnacrttLSGAHPDVTLVRTEALsIGVDEVRELVRRAAMNPVH--GCHQVVVVEDADRITERGADALLKAIEEPAPKTVWLLCAPTPEDVIVTIRSRCRRLHLATPRDEAVADLL---TRRDGI--APEVAAEAARAGQGHIGRARRLAWDEEARAR()}*

_0].
[0_(1)=MiscG_DP(1){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$1=209(209):
>Gamma_DP consensus seq
{()YQVLYRKYRPQTFADVVGQEHVVTTLKNALQNGRVAHYLFSGPRGVGKTTIARILAKALNDEGTHPDVIEIDAASNRGVDDIRELLREKVGYAPVEGGRYKVYIIDEAHMLTEAAFNALLKTLEEPPAHVVFILATTEPEKILPTILSRCQRFNFRRIPVEEIVERLEEIANAEGITADDEALELIARAAQGSMRDALSLLDQAIAFSD()}*

_0].
[0_(1)=AAA(31){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$52=209(209):
>T3_AAA_Family consensus seq
{()SGMIVEEKPNVTWDDIGGLEEQKEELKEAVELPLKHPVLLYGPPGTGKTLLAKAVANEAGGGGSKATFIRVSGSELVSVGEGEKLVRELFELARENAALPSIIFIDEIDAIDGEVQRTLLNQMDGFDSRVKVIAATNRPDTLDPALLRRFRKIEIPLPDEEGRLEILKIHLRKSMKLAEDVDLEELAEKTEGFGADLKALCTEAALLAI()}*

$53=235(209):
>AAAfamily consensus seq for AAA_FAMILY/AAAGoldGold.cma
{()SGDIVEEDPNVTWDDVGGLEEAKEELKEAVEL-LKHPelfeklgikppkgVLLYGPPGTGKTLLAKAVANECG-----ATFFSVSGSELLSkyVGESEKLVRDLFEEARENA--PSIIFIDEIDAIgpkrgdsnsggGGESDRVVnqlLVQMDGFDGRgnVLVIGATNRPDAIDPALLRpgRFdRQIYIPLPDEKGRAEILKIHLRK-MKLAEDVDLEELAAKTEGYsGADLAALCTEAALLAI()}*

$54=234(209):
>ATAD1 consensus seq for ATAD1/atad1Gold.cma
{()AQLVDPLDVGIAWSDIGGLEETCAELKDTVILPIKKKhlfagsnllqppkgVLLYGPPGCGKTLIAKATAKEAG-----CRFINLQVSALTDkwYGESQKLAAAVFSLAAKFQ--PCIIFIDEIDSFlrsrashdHEATAMMKaqfMTLWDGLITDgdcqVIVMGATNRPQDVDAAILRRMpARFHVGQPAAKQRAGILKLILKN-EGVDSDVNLGKIAQKTEGFsGSDLKEVCRNAALYRV()}*

$55=238(209):
>Katanin consensus seq for KATANIN/kataninGold.cma
{()ERDIVQRNPNVHWDDIAGLEEAKRLLEEAVVLPMWMPdffkgirrpwkgVLMVGPPGTGKTMLAKAVATECG-----TTFFNVSSSTLTSkyRGESEKLVRLLFEMARFYA--PSTIFIDEIDSIcsrrgtgsEHEAsRRVKselLVQMDGVggasdgeDPSkmVMVLAATNFPWDIDEALRRRLeKRIYIPLPTAEGRKELLKINLRE-VELAPDVDLEDIAEKLEGYsGADITNVCRDASMMAM()}*

$56=249(209):
>NSF_D1 consensus seq for NSF/NSFd1Gold.cma
{()RQSIINPDWDFEKMGIGGLDKEFSDIfRRAFASRVFPPelveqlgikhvkgILLYGPPGTGKTLMARQIGKMLN-----AREPKVvNGPEILNkyVGESEANIRKLFadaeeeqkRKGDNSG--LHIIIFDEIDAIckqrgsmaggTGVHDSVVnqlLSKIDGVEQLnnILVIGMTNRKDMIDEALLRpgRLeVQMEISLPDEAGRLQILKIHTAK-MrennKLSPDVDLAELAALTKNFsGAELEGLVKAAQSFAM()}*

$57=220(209):
>NSF_D2 consensus seq for NSF/NSFd2Gold.cma
{()IQNGIINWGPPVTRVLDDGELLVEQVKNSDRTPLV-SVLLEGPPGSGKTALAATIAKE-----SDFPFIKIISPEDM-VGFSESAKCQAIKKIFddAYKSPLSCVVVDNIERLldyvpigprfSNLVLQALLVLLKKAPPkgrKLLVIGTTSERDVLEEmDMLDAFStTIHVPNIsTGEEILEVLEELGIFSDDERTTIAGAAGGKTVGIGIKKLLMLIEMARQTDP()}*

$58=233(209):
>PEX1_D1 consensus seq for PEX1/pex1d1Gold.cma
{()SSASETEVNDGVFQDLGGVSRLGKTASDHITLPLAAGqlfeslpiegpggVLLCGGPGSGKTALAKALANEAS-----AHVKYIDCSTLKGkkVENIRKILEEAFSEAAWRA--PSIIILDDLDAIspnegeqseavTS---ALLaqfLTDVNSICGSgqVAVIATCQSSTSINQSLRSshLFdCVISIPAPDKEERAEILSHVKQN-LKAAEDVNFDYLAAKTEGYvAADLEILVERATHAAS()}*

$59=233(209):
>PEX1_D2 consensus seq for PEX1/pex1d2Gold.cma
{()RGVKLHKGSNVKWSDIGGLADVKQVLKETLEWPTKYPeifancplrlrsgVLLYGPPGCGKTLLASAIANECG-----LNFISVKGPELLNkyIGASEQAVRDVFERAQAAK--PCVLFFDEFDSIapkrghdlTGVTDRVVnqlLTQLDGVEGLtgVYVLAATSRPDLIDPALLRpgRLdKSLYCPIPDEADRLDILTALSRK-MNLAEDVDLKEIATKTEGFtGADLQALLYNAQLEAV()}*

$60=230(209):
>PEX6_D1 consensus seq for PEX6/PEX6d1Gold.cma
{()PVPRLPSGKSTPWSSLSPPGLEAL-VSELCAV-LKPPlqpggllltgtssVLLRGPPGCGKTTLVRAACSELG-----LHLLEIDCYDLLNktSGAVEGKLRARFSRARSCR--PAVLLLTHIEALgrdrdglgeDASVVATLrqlLLDEDGLSSCppLVVVATTNDVDKLPEAVRSRFkHEIEVPVPSEAERLEILQALTRG-LPLGPDVDLSSLALQTAGLvAGDLVALVERASRAAC()}*

$61=237(209):
>PEX6_D2 consensus seq for PEX6/PEX6d2Gold.cma
{()SSIGAPKIPNVSWDDVGGLADVKGEILDTIQLPLEHPelfssglkkrsgILLYGPPGTGKTLLAKAVATECS-----LNFLSVKGPELINmyIGESEANVREVFQKARDAK--PCVIFFDELDSLapnrgnsgdsGGVMDRVVsqlLAELDGLsKSGdgVFVIGATNRPDLLDPALLRpgRFdKLLYLGIsSDRASQLNILQALTRK-FKLDNDVDLSEVAELCPfNLtGADFYALCSDAMLNAM()}*

$62=235(209):
>PLANT1_AAA consensus seq for PLANT1_AAA/Plant1Gold.cma
{()ADVIPPNEIGVTFDDIGALENVKETLKELVMLPLQRPelfckgqllkpckgILLFGPPGTGKTMLAKAVATEAG-----ANFINISMSSITSkwFGEGEKYVKAVFSLASKIA--PSVIFVDEVDSMlgrrenpgeHEAMRKMKnefMVNWDGLRTKdkerVLVLAATNRPFDLDEAVIRRLpRRLMVNLPDAENREKILKVILAK-EELAPDVDFDELANMTEGYsGSDLKNLCVTAAYRPV()}*

$63=235(209):
>PLANT_AAA consensus seq for PLANT_AAA/plantGold.cma
{()SDVIPPNEIGVTFDDIGALENVKETLKELVMLPLRRPelfckggllkpckgILLFGPPGTGKTMLAKAVATEAG-----ANFINISMSTITSkwFGEGEKYVKALFSLASKVA--PSIIFVDEVDSMlgqrenpgeHEAMRKMKnefMSHWDGLRTKdgerILVLAATNRPFDLDEAVIRRLpRRIMVGLPDAENREKILKVILAK-EKLAEDLDFEELANMTEGYsGSDLKNLCVTAAYRPI()}*

$64=233(209):
>spastin consensus seq for SPASTIN/spastGold.cma
{()MNEIVDGGTAVKWDDVAGQDAAKQALQEIVILPSLRPelftglrapargLLLFGPPGNGKTMLAKAVAAESN-----ATFFSISAASLTSkyVGEGEKLVRALFAVARELQ--PSIIFIDEVDSLltersegEHDAsRRLKtefLVEFDGVqsngDERVLVMGATNRPQELDDAALRRFvKRVYVGLPDLETRLSLIKNLLCK-QGCSlTQQELARLAEFTQGYsGSDLTALAKDAALGPI()}*

$65=236(209):
>VCP_D2 consensus seq for VCP/vcpd2Gold.cma
{()LRETVVEVPTVTWEDIGGLEGVKRELQETVQYPVEHPekfekfgmapskgVLFYGPPGCGKTLLAKAIANECQ-----ANFISIKGPELLTmwFGESEANVREIFDKARQAA--PCVLFFDELDSIaksrgsssgdaGGAGDRVInqiLTEMDGMSAKknVFIIGATNRPDIIDPAILRpgRLdQLIYIPLPDEKSRVAILKACLRK-SPVAKDVDLEFLAKKTQGFsGADLTEICQRACKLAI()}*

$66=233(209):
>VPS4 consensus seq for VPS4/vps4Gold.cma
{()SGAIVSEKPNVKWDDVAGLEGAKEALKEAVILPIKFPqlftgkrkpwkgILLYGPPGTGKSYLAKAVATEAnN-----STFFSVSSSDLVSkwLGESEKLVKNLFELARENK--PSIIFIDEVDSLcssrsdnESEAaRRIKtefLVQMQGVgndNDGVLVLGATNIPWALDSAIRRRFeKRIYIPLPDAHARAKMFKLHLGT-TPNSlTDEDFRELGQRTEGYsGSDISILVRDALMQPV()}*

$67=236(209):
>Prs6B consensus
{()SMLGSDEKPDVTYADIGGLDIQKQEIREAVELPLTHFelykqigidpprgVLLYGPPGTGKTMLAKAVAHHTT-----AAFIRVVGSEFVQkyLGEGPRMVRDVFRLAKENA--PAIIFIDEIDAIatkrfdaqtgaDREVQRILlelLNQMDGFDQTvnVKVIMATNRADTLDPALLRpgRLdRKIEFPLPDRRQKRLIFSTITSK-MNLSEEVDLEDYVARPDKIsGADIAAICQEAGMLAV()}*

$68=236(209):
>PRS consensus seq for PRS/prsGold.cma
{()SVMEVDEKPTETYSDVGGLEKQIQEIKEVVELPLKHPelfeemgidppkgVLLYGPPGTGKTLLAKAVANQTS-----ATFIRVVGSELVQkyIGEGARLVRDIFKLARENA--PSIIFIDEIDAIgtkrfdsnsggDREVQRTMlelLNQLDGFDDRgnVKVIMATNRIDTLDPALLRpgRIdRKIEFPLPDLSGRAEILGIHSSK-MNLAEDVNLETLATTTDGLsGADIKAVCTEAGMLAL()}*

$69=228(209):
>Ycf46 consensus
{()SGILEFFEADSSQDDIGGLENLKVWLNQ--RY-RAFSkeardyglpipkgVLLVGVQGTGKSLTAKAIAKSWS-----MPLLRLDVGRLFSglVGSSEARTREAIQRAEAMS--PCILWIDEIDKGfggdarsdGGTSQRVLgslLTWM--AEKEspVFVVATANAIDKLPPELLRkgRFdEIFFVDLPNSEERLSIFDLHLKK-RRPDLSFDLSTLADRTEGFsGAEIEQAVIEAMHIAF()}*

$70=239(209):
>TBP7 consensus seq for TBP7/tbp7Gold.cma 
{()DIDPLGVDTNVGFDDVGGLDNHIDQLKEMVAFPLLYPevfekfnitpprgVLFHGPPGTGKTLVARALANECSSGGQKVSFFMRKGADCLSkwVGEAERQLRLLFEEAKAMQ--PSIIFFDEIDGLapvrsskqdqiHASIVSTLLALMDGLDNRgqVVVIGATNRPDAIDPALRRpgRFdREFYFPLPDKEARKEILDIHTRKWEPPPSDEFLDELAEKCKGYcGADLKALCTEAALIAI()}*

$71=233(209):
>VCP_D1 consensus seq for VCP/vcpd1Gold.cma
{()REDEEESLNEVGYDDVGGCRKQLAQIRELVELPLRHPqlfkaigvkppkgILLYGPPGTGKTLIARAVANETG-----AFFFLINGPEIMSklAGESESNLRKAFEEAEKNA--PAIIFIDEIDAIapkrekthgevER---RIVsqlLTLMDGLKSRahVIVMGATNRPNSIDPALRRfgRFdREVDIGIPDATGRLEILQIHTKN-MKLADDVDLEQVANETHGYvGADLAALCSEAALQAI()}*

$72=236(209):
>Prs10 consensus
{()YNMSHEDPGNVSYSEIGGLSEQIRELREVIELPLTNPelfqrvgikppkgVLLYGPPGTGKTLLARAVASQLD-----ANFLKVVSSAIVDkyIGESARLIREMFNYARDHQ--PCIIFMDEIDAIggrrfsegtsaDREIQRTLmelLNQMDGFDTLgkVKMIMATNRPDTLDPALLRpgRLdRKIEIPLPNEQARLEILKIHASP-ITKHGEIDYEAIVKLSDGFnGADLRNVCTEAGMFAI()}*

$73=236(209):
>PRS4 consensus seq for PRS4/prs4Gold.cma
{()SVMKVEKAPTESYADIGGLESQIQEIKEAVELPLTHPelyeemgikppkgVILYGAPGTGKTLLAKAVANQTS-----ATFLRVVGSELIQkyLGDGPKLVRELFRVAEENA--PSIVFIDEIDAIgtkrydsnsggEREIQRTMlelLNQLDGFDSRgdVKVIMATNRIETLDPALIRpgRIdRKIEFPLPDEKTKRKIFQIHTSK-MTLAEDVNLEELIMAKDDLsGADIKAICTEAGLLAL()}*

$74=236(209):
>Prs6A consensus
{()KAMEVDEKPTEQYSDIGGLDKQIQELVEAIVLPMTHKekfenlgiqppkgVLMYGPPGTGKTLLARACAAQTK-----ATFLKLAGPQLVQmfIGDGAKLVRDAFALAKEKA--PSIIFIDELDAIgtkrfdseksgDREVQRTMlelLNQLDGFSSDdrVKVIAATNRVDILDPALLRsgRLdRKIEFPHPNEEARARILQIHSRK-MNVSPDVNFEELARSTDDFnGAQLKAVCVEAGMIAL()}*

$75=236(209):
>Prs7 consensus
{()TMMQVEEKPDVTYSDVGGCKEQIEKLREVVELPLLHPerfvnlgidppkgVLLYGPPGTGKTLCARAVANRTD-----ACFIRVIGSELVQkyVGEGARMVRELFEMARTKK--ACIIFFDEIDAIggarfddgaggDNEVQRTMlelINQLDGFDPRgnIKVLMATNRPDTLDPALMRpgRLdRKVEFSLPDLEGRTHIFKIHARS-MSVERDIRFELLARLCPNStGAEIRSVCTEAGMFAI()}*

$76=236(209):
>Prs8 consensus
{()SLMMVEKVPDSTYEMIGGLDKQIKEIKEVIELPVKHPelfeslgiaqpkgVLLYGPPGTGKTLLARAVAHHTD-----CTFIRVSGSELVQkyIGEGSRMVRELFVMAREHA--PSIIFMDEIDSIgssrleggsggDSEVQRTMlelLNQLDGFEATknIKVIMATNRIDILDPALLRpgRIdRKIEFPPPNEEARLDILKIHSRK-MNLTRGINLRKIAEKMPGAsGAEVKGVCTEAGMYAL()}*

$77=236(209):
>PsmR consensus
{()XGMEVIEKPDVTYDDIGGLDEQIQEVREAVELPLTKPelfekvgieppkgVLLYGPPGTGKTLLAKAVANETN-----ATFIRMVGSELVQkyIGEGARLVRELFELAREKA--PSIIFIDEIDAIgakrldsgtsgDREVQRTLmqlLAEMDGFDSRgdVKIIAATNRPDILDPALLRpgRFdRIIEIPLPDEEGRKEILKIHTRK-MNLAKDVDLKKLAELTEGFsGAELKAICTEAGMFAI()}*

$78=238(209):
>Ags32 consensus seq 
{()KKFNNETDIKIKFKDVAGCDEAKEEIMEFVNF-LKNPsqyedlgakipkgAILTGPPGTGKTLLAKATAGEAN-----VPFITVSGSEFLEmfVGVGPARVRDLFATARKNA--PSILFIDEIDAVgrkrgkggfsggNDERENTLnqlLVEMDGFTTTdnVVVLAGTNRPDILDKALLRpgRFdRQINIDKPDIKGRASIFKVHLGN-LKLaGEKFDLsRKLAALTPGFsGADIANVCNEAALIAA()}*

$79=235(209):
>FTSH consensus seq for FTSH/ftsHGold.cma
{()AKMQMEPKTKVTFADVAGVDEAKEELQEIVEF-LKNPekfqklgakipkgVLLVGPPGTGKTLLAKAVAGEAG-----VPFFSISGSDFVEmfVGVGASRVRDLFEQAKKNA--PCIIFIDEIDAVgrqrgaglgggHDEREQTLnqlLVEMDGFEGNegVIVIAATNRPDVLDPALLRpgRFdRQVVVDLPDVKGREEILKVHARN-KPLGPDVDLEVIARRTPGFsGADLANLVNEAALLAA()}*

$80=232(209):
>Yme1p consensus
{()DKEVDPQQQTVRFSDVHGCDEAKAELEEIVDF-LKNPekfsslggklpkgVLLTGPPGTGKTLLARAVAGEAG-----VPFFFMSGSEFDEvyVGVGAKRVRELFAQARAKA--PAIIFIDELDAIggkrnprdAAYAKQTLnqlLTELDGFSQTsgVIIIGATNFPESLDKALTRpgRFdRKVVVDLPDVRGRMDILKHHMKN-VQISTDVDPSIIARGTPGFsGAELENLVNQAAVHAC()}*

$81=243(209):
>StgV consensus
{()GADTLEDALEE-LDSLIGLEEVKEEVRTLINLLKVQqkrkeqglpvppislHMVFTGNPGTGKTTVARLLGEILKelGVLKKGHLVEVDRADLVAGYVGQTAIK---TNEVIESALGGVLFIDEAytlarNDFGQEAIDTLLKLMEDHRDRLVVIVAGYTEEmerflNSNPGLKSRFpNTIEFEDYTPDELVEIAESMAKKKGYELTEEAEEALKERFEelyenrdedfGNGRLVRNLFEKAIRRQA()}*

$82=238(209):
>Ycf2  consensus
{()FYQTITSSQTLCGTNAFHFPSHGKPFSLRLGLSPSKGILLIGPIGTGRSYLIKSLAANSY-----VPLIRISLKKLiygdaLYnfKPESILWKRSLdqfslqLELAKAMS--PCIIWIPNIHDLnlndstdflEGDPTFLLgglLNSLSGDSEKsstrnILVIASTHIPKKVDPALIApnRLnTCINIRRLLIPQRQKEFFILLRT-KGFhleKEIFDTNEFGSITIGYnTRDLAALANEALLISI()}*

_0].
[0_(1)=ClpLon(13){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$83=209(209):
>T5_ClpLonFamily consensus seq
{()CEELLEEAEEGLDDPVIGQDKAKEAVSEALRRRRKGNVLFVGPTGVGKTELAKGLAERLFNEEGDVPFIRLDMGELTEVGYFEGDLKQALRKLVVAGAPNGILFIDEIDKLHPDVQNALLPALDGGTSNVIFIGATNLDEEKDPALRNRFEIVEVNPLTEEDTVKILKGLLEGVELEFTDEALEAIAELAARGARPLPDKIIDLIDEAA()}*

$84=234(209):
>ClpA1 consensus
{()CVNLNEKAKEGKIDPLIGRDKEVERTIQILCRRRKNNPLLVGEPGVGKTAIAEGLAKRIVE--GEVPevladatIYSLDMGALLAgtkyRGDFEKRLKAVLKELE-K-DPNAILFIDEIHTIIGagatsggamDASNLLKPALSSGK--LRCIGSTTYKEyrgifEKDRALSRRFQKIDVNEPSVEDTIKILKGLKSRFEEHhnvkYTDEALKAAVELSARYIndRKLPDKAIDVIDEAG()}*

$85=272(209):
>ClpA2 consensus
{()DKEVLKNLERDLKRVVFGQDKAIEALSSAIKLSRAGlrepdkpigSFLFAGPTGVGKTEVAKQLAKIL-GIE----LLRFDMSEYMErhtvsrligappgyVGFDQGgLLTDAVDKH-----PHCVLLLDEIEKAHPDVFNILLQVMDHGtltdnngrkadFRNVILIMTTNagaeemakasigftrqdrsgdameaIKRLFTPEFRNRLdAIISFNPLDEEVILQVVDKFLLeleaqlddkKVTLEVSDEAREWLAEKGydpLMGARPMARVIQEHIKKPL()}*

$86=234(209):
>ClpB1 consensus seq for CLPB/ClpB1_Gold.cma
{()GRDLTELAREGKLDPVIGRDEEIRRVIQILSRRTKNNPVLIGEPGVGKTAIVEGLAQRIVN--GDVPeslknkrVISLDLGALVAgakyRGEFEERLKAVLKEVK-ESEGEVILFIDELHTLVGagaaegamDAANLLKPALARGE--LRCIGATTLDEyrkyiEKDAALERRFQPVYVGEPSVEDTISILRGLKERYEVHhgvrITDSALVAAATLSDRYIsdRFLPDKAIDLIDEAA()}*

$87=274(209):
>ClpB2 consensus seq for CLPB/ClpB2_Gold.cma
{()EREKLLHMEEELHERVVGQDEAVKAVSDAIRRARAGlkdpnrpigSFLFLGPTGVGKTELAKALAEFLFDSE--DAMIRIDMSEYMEkhsvsrligappgyVGYEEGgQLTEAVRRR-----PYSVVLFDEIEKAHPDVFNILLQILDDGrltdsqgrtvdFKNTIIIMTSNigseiilegdgsdyeeikeevmeeLKQYFRPEFLNRIdEIIVFNPLTKEEIKKIVDIQLKrlrkrladrGITLEVTDAAKEWLAEEGydpVYGARPLKRAIQRLVENPL()}*

$88=214(209):
>ClpL consensus
{()GANDIERLKDRLLDKVIGQDKAVEEVARAIRRNRANRPIFVGPTGVGKTELAKQLALDIF--GGKDAIIRLDMSEYedRTAYVGYEDNSNTL-TERVRRNPYSILLFDEIEKADPQVITLLLQVLDDGRltdgqgnqdnfKNTIIIATSNAG----------FGNEVVNAPSAADTFEIMDGIkpllNRFNAVILPKEDLKAIVDLMLQYVQRTLpKKAIDLVVSTA()}*

$89=209(209):
>ClpLon consensus seq for CLP_LON/ClpLonGold.cma
{()RQPLTELAEEGLLDPVIGQEEAKEAVIEALRRRRKGPVLFVGPPGVGKTELAKGLAQRLFNEEGDVPFIRLDMGELTEVGYFEGRLKQLLRKLSIKQAPNGILFIDEIDKLHGDVQNALLPALDDGESNVLFIGATNLDEEKDPALLRRFEIVEVSELTEEETVEILRGLLKGYELHFTDEALEAIAELASRGARPLPDKIIDLIDEAA()}*

$90=319(209):
>ClpX consensus seq for CLPX/ClpX_Gold.cma
{()RVPKPKEIKAHLDQYVIGQERAKKVLSVAVYNHYKrinagqkdddvelekSNILLIGPTGSGKTLLAQTLAKIL-----DVPFAIADATTLTEAGYVGEDVENILLRLlqaadyDVEKAQRGIIYIDEIDKIarksenpsitrdvsGEGVQQALLKILEGTvanvppqggrkhphqefiqvdTTNILFICGGAFvgldkiikkrlgkksigfgaeekskSEDrsellkqvepedlikfgLIPEFIGRLPVvVTLDPLDEDALVRILTEpknalvkqyqklfEMDGVELEFTEEALKAIAQLAlerKTGARGLRAIIENIMLDVM()}*

$91=364(209):
>LonH consensus
{()FETTEDiEVPKRLIDQVIGQEHAVEVIKKAAKQRR--HVMLIGEPGTGKSMLAKAMAELLPKEEledilvypnpedenepkirtvpagkgkeivdahkeearkqrqmrnrllmiiifgiigygviiltllfgiiaaafiymalrylgpkeeamipkllvknddkETAPFVDATGA---HAGALLGDVRhdpfqsggletpahDRVEAGAIHKAHKGVLFIDEINTLRLESQQALLTAMqekefpitgqserssgamvktEPVPCDFILVAAGNLDaiQGMHPALRSRIrgygYEVYMNdtmPDTPENRRKLVRFIAQEVkkdgkIPHFDKSAVEEIIREAQRRAgrkghltlrlRDLGGLVRVAGDIAR()}*

$92=263(209):
>TorsinA consensus
{()CSFARTGLEKDLDVKLFGQHLAKKVVLKAV---KGFlnnpkpkkplVLSFHGWTGTGKNFVSKIIAENLYRDG-----LR---SDYVHlfvatlhfphpsnVDlYKE-QLQSWIRGNVSAC-ARSLFIFDEMDKMHPGLIDVLKPFLDYYdvvdgvsYRKAIFIFLSNaggerinevaldfwragrsreeitlkdLEPVLSVEVFNNKNSGfwhsglidENLIdYFVPFLPLEYKHVRLCVRAEMLSRGYEPDEEIVDEVADEMTYFPKEERLFSS()}*

$93=406(209):
>HslU consensus seq for HSLU/HslUGold.cma
{()SEMTPREIVSELDRHIIGQDDAKRAVAIALRNRWRrmqlpeelrdevtpKNILMIGPTGVGKTEIARRLAKLA-----NAPFIKVEATKFTEVGYVGRDVESIIRDLvdaavkmvreqerekvraraeeaaeerildallppaksewgeeeeteedsatrqkfrkklregelddkeieievaaappgveimappgmeemtnqlqdmfgnlgggktkkrklkvkearkllieeeaaklvdqeelkqeaieaV---EQNGIVFIDEIDKIakrgessgadvsREGVQRDLLPLVEGStvstkygmvkTDHILFIASGAFhvakPSDLIPELQGRLPIrVELDALTEEDFVRILTEpkasltkqykallKTEGVTLEFTDDAIRRIAEIAwqvnesteNIGARRLHTVMERLLEEIS()}*

$94=262(209):
>Lon2 consensus seq for LON2/lon2pGold.cma (ok)
{()TEPLAEKLRPTSFEEIVGQEDGIKALKAALCGPNPQHVIIYGPPGVGKTAAARLVLEEAKKNPsspfkEDAKFVEVDGTTLRFdergiadplIGSVHDPIYQGAGALGEAGipqpkpgavtdAHGGVLFIDEIGELHPIQMNKLLKVLEdrkvflesayyssedtnipkyikdifqnGLPADFRLIGATTRSPEEIpPAIRSRCLEVFFRPLTPEEIAKIAKNAAEKIGVKL-EEGVLELIARYAINGREAVNIVQIAAGLAT()}*

$95=248(209):
>Lon consensus seq for LON/LonGold.cma
{()MSEDLKKAREILDEDHYGLEKVKERILEYLAVRKLkgslkgPILCLVGPPGVGKTSLGKSIARALGRK-----FVRISLGGVRDeaeirghrrtyVGAMPGRIIQALKKA---GTSNPVFLLDEIDKLgsdfRGDPASALLEVLDPeqnstfsdhyldvpfDLSKVLFIATANSLT-IPAPLLDRMEIIELSGYTEEEKLEIAKRYlipkqlkengLKEDELSITDEALRKIIRHYtrEAGVRNLEREIGKICRKVA()}*

_0].
[0_(1)=NtrClike(19){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$96=209(209):
>T6_NtrC_Family consensus seq
{()QANRELEAGSSGFEGIIGNSMQELRELIEKVAPSDATVLITGESGTGKELVARAIHALSPRAKIDGPFVAVNCAALPESLLESELFGGRFELADAAKGNGGTLFLDEIGELPLALQAKLLRVLQEGPVDVRIIAATNRDGRFREDLYYRLVTIELPPLRREDIPLLAEHFLERFVKGISPEALAALLYDWPGNVRELRNVIERAVILAE()}*

$97=248(209):
>NtrC  consensus
{()QQQAPAEEEEAETPEIIGEApaMQEVFRAIGRLSQSSITVLINGESGTGKELVARALHRHSPRA--NGPFIALNMAAIPKDLIESELFGhekgaftgantrrqGRFEQAN-----GGTLFLDEIGDMPLDTQTRLLRVLADGefyrvgghtpiKVDVRIIAATHQNleqlvqqGLFREDLFHRLnvIRLHLPPLreRREDIPLLARHFLQRAakelgvePKRLSPEALEYLTrLPWPGNVRQLENTCRWLTVMAP()}*

$98=247(209):
>PrpR  consensus
{()MTGYADARGASDFGDIIGQSpqMEQVKQTITLYAPSRAAVLIEGESGTGKELVARAIHQLSGR---QGPFVPVNCGAIAPELLESELFGheegaftgakggreGLFEIAH-----GGTLFLDEIGEMPLPMQTRLLRVLEQKavrpvgsekevPVDVRVIAATNRNldeeveqGRFRRDLFYRLnvLRITLPPLreRPEDILPLAEHFTKQLlaelgvpFVEWSHEDLTALQaYDWPGNIRELRNMIERCILLGK()}*

$99=248(209):
>NifA consensus
{()XXXDELLRERYGFENIIGKSpaMQEVLELIEKVAPSDATVLIRGESGTGKELVARAIHYNSPRK--DKPFVAVNCAALPESLLESELFGhekgaftgavkrrkGRFELAD-----GGTLFLDEIGEISLALQAKLLRVLQERefervggtktiKVDVRIIAATNRDleemvaeGRFREDLYYRLnvVPIELPPLreRREDIPLLAEHFLEKFarenekrVKGISPEALDLLMaYDWPGNVRELENVIERAVILSK()}*

$100=248(209):
>ZraR consensus
{()SIDAETPAVSASQFGMIGKSpaMQHLLSEIAMVAPSEATVLIHGDSGTGKELVARAIHASSARS--DKPLVTLNCAALNESLLESELFGhekgaftgadkrreGRFVEAD-----GGTLFLDEIGDISPLMQVRLLRAIQERevqrvgsnqtiSVDVRLIAATHRDlaaevsaGRFRQDLYYRLnvVAIEVPSLrqRREDIPLLAGHFLQRFaernrkaVKGFTPQAMDLLIhYDWPGNIRELENAVERAVVLLT()}*

$101=239(209):
>BCS1 consensus seq for BCS1/bcs1Gold.cma
{()KTVIYTAVGAEWRQfghprrrrpinsvvlDGGIAETIIQDVKEFINNakwysdrgiPYRRGYLLYGPPGCGKSSFITALAGEL-----DYSICILNLSE-------RGLTDDRLNHLLNVAPQQSIILLEDIDAAFvsrelssengaasRVTFSGLLNALDGVASTEerIVFMTTNHIERLDPALIRpgRVDVKQLIGDASAYQAEQMFLKFYPNETDEAeNFVEKVLSHKKTVSMAQIQGHFMMHKNDPD()}*

$102=236(209):
>RbscAct consensus
{()TYNLDNTMDGFYIAPAFMDKLVVHITKNFMTLPNIKVPLIlgiWGGKGQGKSFQC-----ELVFAKMGINPIMMSAGELEsgNAGEPAKLIRQRYREAAdiIKKGKMCCLFINDLDAgagrmggttqytVNNQMVNATLMNIADNPTNVqlpgmynkeenprvPIIVTGNDFSTLYAPLIRdgRMEKFYW-APTREDRIGVCKGIFRTDNV--PDEDVVKLVDTFPGQSIDFFGALRARVYDDE()}*

$103=246(209):
>dctD consensus
{()KRRLVLENRLEPRLIGRSPAMQRLRELIANVADTDADVLIEGETGTGKELVARALHDLSRRR--DGPFVAINCGALPESLFESELFGheagaftgaqkrriGKIEHAN-----GGTLFLDEIESMPLALQVKLLRVLQERvverlgsnqsiPVDIRVIAATKVDlkelaaaGRFRADLYYRLnvVTLELPPLreRREDIPLLFEHFLLQAaarygrpAPALSAAQRARLLsHDWPGNVRELRNAAERFVLGLS()}*

$104=241(209):
>TyrR  consensus
{()QLQALQKQDLSGFEQIVAVSpkMKAVVEQARKLAMLDAPLLITGETGTGKELLARACHLASPRR--EKPFLALNCASLPDDVAESELFGyapggkkGFFEQAN-----GGTVFLDEIGEMSPRLQAKLLRFLQDGtfrrvgedeevHVDVRVICATQKNlaelvqeGEFREDLYYRLnvLTLNIPPLreRKQDIMPLAELFVAQFsqqlgvpRPKLSADLLDALTrYAWPGNVRQLKNAIYRALTLLE()}*

$105=209(209):
>bEBP consensus seq
{()EELRRLLEERYGFDGIIGESMQEVLELIRRVAPSDATVLITGESGTGKELVARAIHQLSPRAGQDGPFVAVNCAAIPENLLESELFGGLFELADAXXXXGGTLFLDEIGELPLALQAKLLRVLQERKVDVRIIAATNRDGRFREDLYYRLVPIHLPPLRREDIPLLAEHFLERFVKGLSPEALEALLYDWPGNVRELRNVIERAVILAE()}*

$106=248(209):
>NTRC consensus seq NTRC/ntrCGold.cma (ok)
{()EELRLRLAKSSTFEDLIGRSpaMRRLLQLARRVAPTDAPVLITGETGTGKELVARAIHALSPRA--DGPFVAVNCAAIPESLLESELFGhekgaftgassgrkGLFELAD-----GGTLFLDEIGELPLELQAKLLRVLEEGefrrvggtkpiPVDVRIIAATNRDleelveeGRFREDLYYRLnvVEIHLPPLreRREDIPLLADHFLDRFarkygkpVKGLSPEALAALLaYDWPGNVRELRNVIERAVVLSE()}*

$107=244(209):
>DhaR consensus
{()LMTSQLGKVSHTFAHMPQDDpqTRRLIHFGRQAARSSFPVLLCGEEGVGKALLSQAIHNESERA--AGPYIAVNCQLYGDAALAEEFIGsdrtdnengrlSRLELAH-----GGTLFLEKIEYLAPELQSALLQVIKQGvitrldarrliPVDVKVIATTTADlamlveqNRFSRQLYYALhaFEITIPPLrmRRGDIPALVNNKLRSLekrfstrLK-IDDDALARLVsYAWPGNDFELYSVIENLALSSD()}*

$108=234(209):
>FisDctD consensus
{()ALRRELSDGSQIMKKLIGSSpvMERLREDILDLGQADGHVLIEGETGTGKTLVAHALHAVGARA--GKKFVLVSCSAYDEEALSRRLFGpmepedsflPAFEEAR-----GGTLVLEDIEALSEALQAKLLTKINEQgtPAETRIIAISNLQepgktceDALRPDLYYRLaaLKITVPPLrqRGEDILTLFTRYSEQFaeeygcdAPQVTAQEAAQLLqAPWPGNVRQLINVAERAVLQSR()}*

$109=248(209):
>Fis consensus
{()XXXXXXKKKVLKNYEWIGNSkaIRELRNLIEKVAITDARVLITGENGTGKELVAHIIHEKSNRS--KGPFIEVNCAAIPSELIESELFGhekgsftsalkdrrGKFEAAN-----LGTLFLDEIGDMSLTAQAKVLRALQENkiqrvgsekdiKVDVRVIAATNKDlkkeiikGNFREDLYHRLavILIEVPPLneRKEDIPLLVDHFLKKIskeqgieTKKFSKDAIKLLKkYDWTGNVRELRNVVERLIILGG()}*

$110=247(209):
>FleQ consensus
{()RAERRSARRTNLFRSLVGTSrgIQEVRHLIEQVADTDASVLILGESGTGKEVVARNIHYHSKRR--DGPFVPVNCGAIPAELLESELFGhekgaftgaitsrkGRFELAE-----GGTLFLDEIGDMPLPMQVKLLRVLQERtfervggnktiKADVRIIAATHRNletmiedGTFREDLYYRLnvFPIEMPALreRKEDIPLLLQELISRMeaegrgSIRFTSRAIESLCeHDWPGNVRELANLVERLAILYP()}*

$111=253(209):
>LevR  {|9(3)|}consensus
{()QLVRPVLFLHDPFDTLIGYNgsLKEAIEQAKAAIlypPNGLHTLLLGETGVGKSFFAELMYEYAIESKIlpkDAPFIVFNCAdyANNPQLLLSQLFGhvkgaftgadedkkGLVEKAD-----GGILFLDEVHRLPPEGQEMLFTFMDKGeyrrlgetenerKANVRIIFATTEDpESFLLKTFLRRipMTITLPSLreRtLEERLELIKLFFTREakrlnktI-SISKNALKALLlYDCPGNIGQLKSDIQLACAKAF()}*

$112=243(209):
>NtrXL  consensus
{()KENKELENKLFHSYELIGNSknILNIKDQIEKISITESRVFISGPSGSGKELIARKIHKNSKRS--KNPFVIINGALLDLDKYELELFGeekengsisyGALEKAN-----KGTLLIDEVSEIPLETQSKILRVLIDQkfkrvngnndiNVDVRLICSSSKDlkkeikiGNFREDLFHRLnvFEINIEPLnqRISDIPLLIKYFSKKIsenynikELDI-DENNSYLLnHNWPGNVRELRNLIERIAILQP()}*

$113=257(209):
>RtcR consensus
{()FAEERQETLDFLKSGIATRNphFNRMIEQIERVAiRSRAPILLNGPTGAGKSFLARRIYELKQAR--HqfsGAFVEVNCATLRGDTAMSTLFGhvkgaftgareareGLLRSAD-----GGMLFLDEIGELGADEQAMLLKAIEEKrfypfgsdrevSSDFQLIAGTVRDlrqlvaeGKFREDLYARInlWTFTLPGLrqRQEDIEPNLDYELERHaretgdsV-RFNTEARRAYLaFAtspqatWRGNFRELSASVTRMATLAD()}*

$114=301(209):
>MgChelatase consensus seq for MG_CHELATASE/MgChelataseGold.cma (ok)
{()MADTKESARPVFpFTAIVGQEEMKLALLLNAIDPKIGGVLIMGDRGTGKSTTVRALADLLPEIEvvagdpfnsdpddpelmsdevrervengeelptekIKVPMVDLP------LGATEDRVCGTLDiekaltegvkafePGLLAKANRGILYVDEVNLLDDHLVDVLLDSAASGwntveregisirhPARFVLVGTGNPEEgELRPQLLDRFgLHVEVRTVrDPELRVEIVERRLAFDadpeaflekyaaeqealrtriiaarellpDVTIDDELLVKISELCielgVDGLRGDLVTNRAAKALAA()}*

_0].
[0_(1)=RuvBlike(4){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$48=209(209):
>T2_RuvBLike consensus seq
{()GGEAAERTRPQSLDEYVGQEAAKEALEELIESAAIDAVLLAGPPGCGKTTLANIIANETGGNNLTATFCALSGSSAYGAGDVKEVAGEAAAELTGSRGKGGVLFIDEIHRLSKACETALNPAVESGTATIIGATATNRAGGVTSALLDRCGIQRLEKYTVEEVTTIVKRAAETEGVEISEEALAELAERADGSARIANNLLTRASDAAQ()}*

$49=222(209):
>RuvB  {|5(7)|}consensus seq for RUVB/ruvBGold.cma (ok)
{()EEEAIERaLRPKSLDEYIGQEKVKEQLEIFIEAAkkrgeALDHVLLFGPPGLGKTTLANIIANEM-GVNLRIT-----------SGPVLEKAGDLAALLTNSLEPGDVLFIDEIHRLSPVVEEVLYPAMEDFQLDImigegpaarsikldlpPFTLvgATTRAGLLTSPLRDRFGIvQRLEFYTVEELTRIVTRSARILGVEIDEEGALEIARRSRGTPRIANRLLRRVRDFAQ()}*

$50=395(209):
>TIP49  {|36(0)|}consensus seq for TIP49/TIP49Gold.cma
{()LGLDEDGTAKQSADGLVGQEAAREAagvVVELIKSKKMagRAILLAGPPGTGKTALALAIAQELGN---KVPFCPMVGSEVYSAEVKKtEVLMENFRRAIGLRIKetkevyegevteltpeetenplggygktishviiglktakgtkqlkldpsiyeslqkekvevgdviyieansgavkrvgrsdayatefdleaeeyvplpkgdvhkkkeivqdvtlhdldvanarpqggqdilsmmgqlmkpkkteitdklrgeinkvvnkyidqgvaelvPGVLFIDEVHMLDIECFTYLNRALESSLAPI-VIFATNRgnctirgtddivsPHGIPLDLLDRLLIIRTLPYTPEEIKQIIKIRAQTEGINISEEALEKLAEIgTKTSLRYAVQLLTPASILAK()}*

$51=232(209):
>WHIP consensus seq for WHIP/whipGold.cma (ok)
{()GAPLAERMRPRTLDEYVGQEHLLGEgklLRRLIESDTIPSLILWGPPGCGKTTLARIIANSTKRN--TARFIALSATSA-GVKDVREVVEEAENELK-MFGRRTILFIDEIHRFNKAQQDAFLPHVEKGTITLIGATTENPSFEVNSALLSRCRVFVLEKLSVESVMTILKRALkdEERGlldsasltnnashlsktsgspnVEVEEEALAHLAELADGDARIALNTLELAVLARM()}*

_0].
[0_(1)=MiscAAAPlus(31){go=10000,gx=2000,pn=1000.0,lf=0,rf=0}:
(209)*****************************************************************************************************************************************************************************************************************

$115=209(209):
>T8_OtherAAAplus consensus seq
{()FRPGVEKLKDEGLDDLVGQDEAKEALLAALELGRAGGLLLVGPPGTGKTTLARALANALGGPNRGASFVRINGSSLTDLQALVGTLKELLDLAKLSAGKNGVLVIDEFDKLDSEVQEALLTLLEGGPANVRIIATSNPPERLPDALLDRFEVLELPPPDREELAEILKTRADREEKLLSDDALEAIAEAYGGSVRELLRLLRAAGELAR()}*

$116=223(209):
>DnaA consensus seq for DNAA/DnaA_Gold.cma
{()ADFAGNLNPKYTFENFVvgpSNRFAHAAALAVAENPGRayNPLFIYGGVGLGKTHLMQAIGNYVRENNPGAKVCYVSSEKFTNdlVNAIRKGKMEEFRNRY---RSVDVLLIDDIQFIagKERTQEEFFHTFNAlYEANKQIVISSDRPPKeipgLEDRLRSRFewgLIADIQPPDLETRVAILQKKAEQEGIELPNEVADYIAENITSNVRELEGALIRLIAYAS()}*

$117=260(209):
>Dynein consensus seq for DYNEIN/DyneinGold.cma
{()FPYGVEYHGVA--ERLLRTPLTDRcrHFYLlYQILRQRHGLLLVGPSGSGKTETLKALLAALNRLE----VVGLNFSSATTPELLVKTCDHYIDYKAmgdlfvvlRPVGLWG--CLDEFNRewndpllsayLEQRIITILRGLEEKpglfrggdvdwlWVENINFVGDDNPPGYAgrsnlPDNVKRLFEVVALMYPSLATLSQIYGTFprcglvwfsdgfdtaemlvgkMVTFYKLSQEQLSPDDQPHYDFSLRELKRVLRGAGEAIR()}*

$118=230(209):
>DynHC1  consensus
{()FIYGYEYLGNT--PRLVITPLTDRCYLTlTQALHLNLGGAPAGPAGTGKTETTKDLGKALGR------------------QVVVFNCSDGLDYKAmgrifkglAQSGAWG--CFDEFNRielevlsvVAQQILTIQDALKEKkkrfifegkeiKLNPTCGIFITMNPGYAgrtelPDNLKALFRPVAMMVPDYALIAEIMLYSegfldarvlarkIVTLYKLCSEQLS--KQDHYDFGLRALKSVLVAAGNLKR()}*

$119=209(209):
>DynHC2 consensus seq
{()FEYGVEYPRVEPAYDELREAIKKVKVLQYETLLVRHGVMLVGPTGSGKTTAWRVLAKALTRLERSVSRAGLNEEIRTNPEIGVKTVYYVINPKATMGELYGXXELDPATRFREIANDEVRGETSKWIENMNTVLDDNANGEIPPNMRLLFEVQDLAVASPATVSRLLGTAWLNRLRSQPEDLGEDEKPHYDYSLKELTDWLRSLMELIR()}*

$120=259(209):
>DynHC3  consensus
{()EIIEVETHKVA--APDVVIPTLDTvrHEALlYTWLAEHKPLVLCGPPGSGKTMTLFSALRALPDME----VVGLNFSSATTPELLLKTFDHYCEYRKtpngvvlapVQLGKWL--VLFCDEInlpdmdkyGTQRVISFLRQLVEHggfwrtsdqtwvKLERIQFVGACNPPTDPgrkplSHRFLRHVPVVYVDYPGPASLTQIYGTFnramlrlipslrgyaepltaaMVEFYTMSQERFTQDIQPHYIYSPRELTRWVRGIYEAIR()}*

$121=271(209):
>DynHC4 consensus
{()LSGDYIPVDQEELRDYVKARlkVFyeeeldvplvlfnevlDHVLRIDRVFRQPQGhLLLIGVSGAGKTTLSRfvAWMNGLSVF-----------------QIKVHRKYTGEDFDEdlrtvlrrsgCKNEKIC--FIMDESNvldsgflermNTLLANGEVPGLFEGdeyaTLMTQCKEGAQReglmlDSHEElykwfTSQVIRNLHVVFTMNPSSEGLKDRAATspalFnrcvlnwfgdwstealyqvgkeFTSKMDLDRANFVAPDSFPVAYRELGNNLMADAAGNILI()}*

$122=291(209):
>MCM consensus seq for MCM/MCM_Gold.cma
{()DPDIYEKLARSIAPSIYGHDDVKKAILLLLFGGVAKNlpdgtklrgdinVLLVGDPGTAKSQLLKYVEKLAP----RAVYTSGKGSSAVGLTAAVVRDPEtgefVLEGGALVLADNGVCCIDEFDKMNDSDRVAIHEAMEqqtisiakagittTLNARCSVLAAANPiygrydpsksleeNINLPAPILSRFdlIFVVLDECDEEKDRRLAKHvvslhsksepsaeepidqellrkyiaYARQIKPRLSDEAAEKLVEAYvelrqddtassgrssiPITVRQLESLIRLSEAHAK()}*

$123=268(209):
>McrBC consensus
{()FGKRINYIKEEYLNDTFLSEEELDELLTLLNRPK--NLILYGPPGTGKTYLAKELAVELIDPNelkdeGRIEFVTFHQSysyedfveGLRPVTDGQieyelkdGIFKEFCEKAKYNspseedPDKNYVLIIDEINRGNiSKIFGELITLIEpdkrggekealsvtlpysgekfSVPENLYIIGTMNTADRsialLDTALRRRFAFVEMMPdpellgLDVEgiDLIELLKALNQRIELLLDRDHTIGHSYFMDEDDDFDLERIFRNKIIPL()}*

$124=247(209):
>Midasin consensus seq for MIDASIN/MidasinGold.cma
{()LWRAVGGSEPSIDESYVLTPSVKRNLENIARAVSAGeyPVLLEGPTGVGKTSLIQYLAAATGNK-----LVRINLHEQTDTQDLLGGYKSDSsgkfewvdgVLVQAMRKGHWIL-LDELNLAPQSVLEALNRLLDDnrelfipetgevvkAHPNFRLFATQNPPgdyggrKGLSRAFRNRFTEIYVDELDSEDLETILSKRC-----PIPPSYLEKLVEFYtqlqkrrnsskvfagkggPFSLRDLFRWLERLRLRKD()}*

$125=215(209):
>SV40_TA consensus seq for SV40_T_ANTIGEN/Sv40_Gold.cma
{()SADILLWMAGVAWYQCLLPDFPDVLFDILKLMVEnvpkKRYWLFKGPVNSGKTTLAAALLSLC-----GGKALNVNCPADK-----LAFELGVAIDQFV-------VVFEDVkgqiglnkDLQsgqgINNldnlrDHLDGSVKVNLEKKHLNkrsqifppGIVTMNEYLLPQTLQAR-FhKVLDF------KCKDYLaQSLEKSE--FLgRKRIIQSGITLLLLLIWNRPVDEFAPSIQGK()}*

$126=260(209):
>Trip13 consensus
{()ANHWVLPAAEFhgLWESLIYDVEIKSRLLDYvtttllfsdkgvdsnLISWNR-VVLLHGPPGTGKTSLCKALAQKLSIRLSSrypyGQLIEINSHSLfskwfSESGKLVTKLFQKIQELIEDKDALVFVLIDEVESLaaarkaalsgnepsdAIRVVNALLTQLDqlKRHPNVLILTTSNITEAIDVAFVDRADIkQYIGPPSAAAIYEIYRSCLEELMKCgiiYPRQQLLTLRELemigfIENNVSKLSLLLLEIAEKSE()}*

$127=208(209):
>AbsR2  consensus
{()MRRSRGSPPGPGWP-LVGRDAELAALAAALRAGS-GGVVLVGDPGVGKTALERAAAR-------GARVLRVAGTEserSVPFGALAQLLPDgaAVLRAVLSLLRPLLLVVDDAHWLDEAS-AALLHFLALDGA-VRLLATARDGEPVPAALTSLWKdglvpRLDLHPLDRAAATELLEAVLGGPAAGSTADRIHDAAGGNPLALRELLRAARAAGTLRG()}*

$128=227(209):
>afg1  consensus
{()LERYQADLARGGFQPDPAQRAAVERLQRLYDELVAAKakrssgwlkllklkkkpkkppkgLYLWGGVGRGKTMLMDLFFDALPvERKRRLHFHRFMQRVHEELHELRGQADPLEPVAKRIAKEARVLCFDEFFVSDIADAMILGRLFEALFARgVVLVATSNiPPDDLYKNGLQRARFLP--------AIALIKQHCDVLNVDSGVDYRLRTLEQAELYHTPLDAEADAALDKAF()}*

$129=294(209):
>AmiB  consensus
{()FRFDPAAVMDCLRAEVLGQDPALQAVEDMLKVVRADiadprrplfSALFLGPTGVGKTEIVRALARALHGDA--DGFCRVDMNTLSQehyaaaltgappgyVGAKEGtTLLDQDKldgspGR-----P-GIVLFDELEKASPEVVHALLNVLDNGllrvasgertyhFRNTLVFMTSNlcaheiqryderrqrlpwrllpvggerrrrdidgmVRarllKTFSPEFVNRLdSVVTFNWIERDVVARLVELEVQrlnrrlekhRCRLEATPEVLAKIARAGfdrQFGARALRRSVRHHLEVPL()}*

$130=214(209):
>GosAfg1 consensus
{()DIQNIIdKLKNQGINLDLSQINLLEKLIKILIKKkfffnffkknSNGGLYIWGDVGRGKTLITQSF---LKeIRENIASFHyiDFMQFIHNELNKNSGTKNPLKKISKSLSKKHKIIFIDEFQVEDVADAMIIGDLLNSLSDSgTKIILTSNaHPDDLYKDGLQRQKFLK--------SIKILKENFNIYKLDGDIDYRTKNINLDSSDSNKIFSDEDIFEFIKE()}*

$131=197(209):
>GosDnaA  consensus
{()KFDYEQNFKDQDFYVSKSNEHAFNLLNSWPK-WEKNFLNIIGEKFSGKTHLINIFLKKFKGIKINAN--DINNDFLKKIKIYENIIIEDLNEKIDENLLYSLInIID---------QDNKYLII---TSKKPIV----DIKFKLNDLNSRSKNFllaKIEKPDDDLIFALILKNLSDRQISIDKKLIDFIIKridRSYGKISDFIYKIDEISLKKK()}*

$132=236(209):
>gspA consensus
{()EKPFSLTPDPRFLFLSARHREALAHLLYGLQEG-EGFILLTGEVGTGKTTLCRKLLEqlpdnvdvaYIPNPTLTPlellraiaDELGLEYP-GADKKQLLDAIQQFL-LELHAAGRRVVLIIDEAQNLSDEvlEELRLLTNLETDSRKLLQIVLVGQPelrERLarpeLRQLRQRiTARYHLRPLTREETAAYIRHrlqVAGRGEPLFTPAALKAIHRASGGIPRLINLLCDRALLAAY()}*

$133=242(209):
>hypo5  consensus
{()DLDRVRAALTAEFPYARAVVDFVLTDLRGRETVRLRPLLLVGPPGSGKSRFARRLGELLGVA-----VWRYDASG-SDdaffggtdrrwNSAEPCHPFRAIARA---RIANPIVLIDEIEKAgtssdNGRLWDALLPFLERetaaryrdpalqaplDLSHVSYIATANSLDGLPSPLRDRFRVIRFPKPTLSDLPALLPGVladiardrgLDARWVpPLDGDELAAIARAWagGS-VRRLRRLVEATLRARD()}*

$134=237(209):
>MshM  {|18(2)|}consensus
{()EAPFSITPNPRFLFLSARHREALAHLLYGLQEG-GGFILLTGEVGTGKTTVCRKLLNqlpdntdtaYILNPYLSPlellaaicDELGLDYPDNADLKQLTDLINQFL-LELHAAGRRVVLIIDEAQALPDEvlEQLRLLTNLETESRKLLQIVLFGQPeldERLarpeLRQLRQRiTFRYHLRPLTLDETAAYIRHrlqVAGRGEPLFSPKALRAIHRASGGIPRLINLLCDRALLLAX()}*

$135=213(209):
>n2B consensus
{()LDSKQTALREELKQLAAALNKPKSLFKFFNQNNLESGIYLYGPVGSGKTMLMNSFCEEL-----TTPKIIIHYQNFMqEIHKSMHKLQTANQKdiipkiAKNYAKQTKVLCIDEFEiKDITDAMIIGRLFNELIKQNIFIFITSNtSPNNLYKDGLQRESFLPFIKIINNTFYVKYLDNQHDYRFDKALGVKEARIIYPLTLENQNKLEKIITDISDN()}*

$136=260(209):
>RfcGosX1  consensus
{()IIMKFYETKFEDYINsnnkKNLHPELNKIYNNFPENiEDLKNLIFYGPSGVGKYTQMLSIIKKYSPSNLKYEkkininynkqnyyfkisdiHFEIDMSLLGCnaKLLWNEIYNQIVDIISSKKNKNGIIVCKNFHKIHSELLEIFYSYMQSLSNNninIKFIILTESISFIPDNILNRCQIISISRPTKTAYNKCLKNKIDKNIKLNNitniknlksnntqlnnkdkkicNKIINEIINYDNIKFLEFRDKLYDIFIYNL()}*

$137=203(209):
>RfcGOSX2 consensus
{()TFPW-QKNNKASFNNFFFSPDNNELISALNNGDD---LFIYGAKGSGKSFLLQAICNEYSSSNKSSLYIPMKEAINLGTEILD-------SLESLD-----LICIDDIDLILSNrewEIALFNLINECLQSNCRLILSGSinplEINFSLPDLLSRikkMESLELYAINDEELLEALKFISQLLSINLGDKELNYLITYSKRNISDLVEILSSLDQLSM()}*

$138=219(209):
>rga3A  consensus
{()KLLSFLSVD---FDDIVGRDADKKEIVSLLtlESDDVSVLGIWGMGGIGKTTLARAVFNDERISDHFDCKAWVCVSDhfdvlKLQKQILSQILGENIDSLNLEKLQKKlkerlsdkryLLVLDDVWNDDREQWEELRGPLSWGGSGSRIIITTRD---KKVASAHGTEVYELEPLSDDEAWELFCRRAFDGQSEPPDELEElGREIVKKCGG--LPLALKTLGSLLR()}*

$139=209(209):
>AAA consensus seq for GOLD_STD_RFC/GoldStdRFCuse.cma
{()RQPLVEKYRPETLDDIVGQEEAKEALKEALKRGRIGHVLLYGPPGTGKTTLARALARELPGESGDVPFIRLNGSELLGVGAVEGRLKGLLRKASIRGAKPGILFIDEIDKLDDDVQSALLRALEGGPARVRLIAATNPPEKLPPALLDRFLIIEVPPPDEEERVEILRRRLKEEEVELSDDALELIARLAGGSARDLINLLRRAAALAA()}*

$140=250(209):
>TniB consensus
{()RLPDDERIQRIRADRWIGYPRAVEALnrLEALLAWpnkqRMPNLLLVGDTNNGKTMIVEKFRRthppssdadqehipvlvvqmpsEPDEIRFYVAILAALGAPLRPRPRLAE--MEQLALALLRKVGVRMLVIDEVHNLlagTSRNQREFLNLLRflGNELRIPLVGVGTRDAYLairsDPQLANRFEPMELPRWEANEDfcSLLASFEaslpLRRPSNLATLEMARYILTRSEGTIGELFHLLMAAAIAAI()}*

$141=247(209):
>Cdc6 consensus seq for CDC6/Cdc6Gold.cma
{()YQSAKLVLNTAVPDRLPCREQEMGEIRSFLKNHicgqKAGSLYISGAPGTGKTACLSRVLQDFKKDgVKGFNSIYINCMSLRSAQAVFpkiaqeigreescrtagsDLMRKLEQKLTASAGPMVLLVLDEMDQLDSKGQDVLYTLFEWpslPNSRLVLIGIANTLD-LTDRILPRLearenckpQLLNFPPYTRNQIAAILQDRLSEASKDqvFDPAAIQLCARKvaaVSGDIRKALDVCRRAIEIVE()}*

$142=228(209):
>nAAA1 consensus
{()XMMKFEGTKN-----YIATDDLKLAVNAAITLER--PLLIKGEPGTGKTMLAEEVAESLGMPLIEWHIksttkaqqglYEYDAvSRLRDSQLGDERVKDISNYIKKGKlweafesDERVVLLIDEIDKADIEFPNDLLQELDRMEFYVyetgetikakhrpIVIITSNNEKELPDAFLRRCFFHYIQFPDRETMQKIVDVHYPKIKKDLVKEALE-----IFFDVRKVPGLKKKPSTSEL()}*

$143=256(209):
>nAAA2 consensus
{()LRQSLERLIDQVNQVLLGKEEQVRLALAALLAG--GHLLIEDLPGLGKTTLAHALARSL-----GLSFQRIQFTSDLLPADILGvsvyDKKSGQFEFHPGPIFTNVLLADEINRAPPKTQSALLEAMEEGqvtvdgvthplPEPFFVIATQNPVEQsgtfpLPESQLDRFlMRLSLGYPSAEAERELLSGRdrrdllaqlepvlspaellalqAEVKQVHASDALLDYIVALVratrqhpgvrlGLSPRASLALLRAAKAWAL()}*

$144=298(209):
>nAAA3 consensus
{()PGEVQAAPYERDLSDVKGQERAKRALEIAAAGG--HHLLMVGPPGSGKSMLAarlpgilpplspaealetsmiHSLAGLLddGGIWRRRPFREPHHTASMAAIVGGGRNAKPGE---ISLAHNGVLFLDELPEFPRKVLETLRQPLETGevtiaranahvtyPARFQLVAAMNPcpcgylgdparacrcspecieryQGRISGPLLDRIdLRIEVPPLafadldlppsgessaTVAERVAAARERqlarfqgrvnADLEGAELErictldaegRDLLERAAERLGLSARGYHRILRVARTIAD()}*

$145=236(209):
>nAAA4 consensus
{()GRLEPVKHPDRIdLDLLVGIDRQRDTLLAnteqFARGLPANNALLWGARGTGKSSLVKAILNEF--AARGLRLVEVDKEDLPDLPDILELLAGRPE--------RFIIFCDDLSfEADESSYKALKAVLDGGiearPDNVLIYATSNRRHLMPEDmienersgeihpseaveekisLSDRFgLWLGFHPPSQDEYLEIVRGYAAQHGLsiaeeELRAEALEWALERGSRSGRVAWQFITDLAGRLG()}*

_0].

