#!/usr/bin/env python2.7

"""Tweak CMA-format-specific aspects/features of a CMA file.

Example:
    cma-tweak foo.cma --iron --level=1 --name=Testfam

"""

from biocma import biocma, cma, utils
from biofrills.consensus import consensus

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord


def main(args):
    def tweak_block(block):
        if args.add_consensus:
            cons = utils.get_consensus(block)
            block['sequences'].insert(0, cons)
        if args.level:
            block['level'] = args.level
        if args.iron:
            # iron each seq
            for sequence in block['sequences']:
                sequence['seq'] = cma.iron(sequence['seq'])
        return block

    blocks = map(tweak_block, cma.parse(args.infile))
    cma.write(blocks, args.output)


if __name__ == '__main__':
    import argparse
    import sys

    AP = argparse.ArgumentParser()
    AP.add_argument('infile',
                    default=sys.stdin, type=argparse.FileType('r'),
                    help="Input file in CMA format.")
    AP.add_argument('-c', '--add-consensus',
                    action='store_true',
                    help="""Add the consensus sequence.""")
    AP.add_argument('--iron',
                    action='store_true',
                    help="""'Iron out' indels to remove deletion/insertion
                    transitions.""")
    AP.add_argument('-l', '--level',
                    default=0, type=int, # require integer...
                    help="""Set the CMA block level. (Only for single-block
                    files.)""")
    AP.add_argument('-o', '--output',
                    default=sys.stdout, type=argparse.FileType('w'),
                    help="Output file -- will be in CMA format.")

    main(AP.parse_args())

